#ifndef BRANCHINIT_H
#define BRANCHINIT_H
#include "TTree.h"
#include "TChain.h"
void InitINTree( TChain * tree );
void InitOUTTree( TTree * tree );
void CopyInputVarsToOutput(std::string prefix = std::string() );
void CopyPrefixBranchesInToOut( const std::string & prefix );
void CopyPrefixIndexBranchesInToOut( const std::string & prefix, unsigned index );
void ClearOutputPrefix ( const std::string & prefix );
void CopynHLTInToOut( std::string prefix = std::string() ); 
void CopyrunInToOut( std::string prefix = std::string() ); 
void CopyeventInToOut( std::string prefix = std::string() ); 
void CopylumisInToOut( std::string prefix = std::string() ); 
void CopyisDataInToOut( std::string prefix = std::string() ); 
void CopyHLTInToOut( std::string prefix = std::string() ); 
void CopyHLTIndexInToOut( std::string prefix = std::string() ); 
void CopybspotPosInToOut( std::string prefix = std::string() ); 
void CopynVtxInToOut( std::string prefix = std::string() ); 
void CopyIsVtxGoodInToOut( std::string prefix = std::string() ); 
void CopynGoodVtxInToOut( std::string prefix = std::string() ); 
void CopynVtxBSInToOut( std::string prefix = std::string() ); 
void CopyvtxbsPtModInToOut( std::string prefix = std::string() ); 
void CopyvtxbsPtModInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputvtxbsPtMod( std::string prefix ); 
void CopyvtxbsSumPt2InToOut( std::string prefix = std::string() ); 
void CopyvtxbsSumPt2InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputvtxbsSumPt2( std::string prefix ); 
void CopyvtxbsTkIndexInToOut( std::string prefix = std::string() ); 
void CopyvtxbsTkIndexInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputvtxbsTkIndex( std::string prefix ); 
void CopyvtxbsTkWeightInToOut( std::string prefix = std::string() ); 
void CopyvtxbsTkWeightInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputvtxbsTkWeight( std::string prefix ); 
void CopynTrkInToOut( std::string prefix = std::string() ); 
void CopytrkP_xInToOut( std::string prefix = std::string() ); 
void CopytrkP_xInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtrkP_x( std::string prefix ); 
void CopytrkP_yInToOut( std::string prefix = std::string() ); 
void CopytrkP_yInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtrkP_y( std::string prefix ); 
void CopytrkP_zInToOut( std::string prefix = std::string() ); 
void CopytrkP_zInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtrkP_z( std::string prefix ); 
void CopytrkVtx_xInToOut( std::string prefix = std::string() ); 
void CopytrkVtx_xInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtrkVtx_x( std::string prefix ); 
void CopytrkVtx_yInToOut( std::string prefix = std::string() ); 
void CopytrkVtx_yInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtrkVtx_y( std::string prefix ); 
void CopytrkVtx_zInToOut( std::string prefix = std::string() ); 
void CopytrkVtx_zInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtrkVtx_z( std::string prefix ); 
void Copytrkd0InToOut( std::string prefix = std::string() ); 
void Copytrkd0InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtrkd0( std::string prefix ); 
void Copytrkd0ErrInToOut( std::string prefix = std::string() ); 
void Copytrkd0ErrInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtrkd0Err( std::string prefix ); 
void CopytrkdzInToOut( std::string prefix = std::string() ); 
void CopytrkdzInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtrkdz( std::string prefix ); 
void CopytrkdzErrInToOut( std::string prefix = std::string() ); 
void CopytrkdzErrInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtrkdzErr( std::string prefix ); 
void CopytrkPtErrInToOut( std::string prefix = std::string() ); 
void CopytrkPtErrInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtrkPtErr( std::string prefix ); 
void CopytrkQualityInToOut( std::string prefix = std::string() ); 
void CopytrkQualityInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtrkQuality( std::string prefix ); 
void CopynGoodTrkInToOut( std::string prefix = std::string() ); 
void CopyIsTracksGoodInToOut( std::string prefix = std::string() ); 
void CopypfMETInToOut( std::string prefix = std::string() ); 
void CopypfMETPhiInToOut( std::string prefix = std::string() ); 
void CopypfMETsumEtInToOut( std::string prefix = std::string() ); 
void CopypfMETmEtSigInToOut( std::string prefix = std::string() ); 
void CopypfMETSigInToOut( std::string prefix = std::string() ); 
void CopypfType01METInToOut( std::string prefix = std::string() ); 
void CopypfType01METPhiInToOut( std::string prefix = std::string() ); 
void CopypfType01METsumEtInToOut( std::string prefix = std::string() ); 
void CopypfType01METmEtSigInToOut( std::string prefix = std::string() ); 
void CopypfType01METSigInToOut( std::string prefix = std::string() ); 
void CopyrecoPfMETInToOut( std::string prefix = std::string() ); 
void CopyrecoPfMETPhiInToOut( std::string prefix = std::string() ); 
void CopyrecoPfMETsumEtInToOut( std::string prefix = std::string() ); 
void CopyrecoPfMETmEtSigInToOut( std::string prefix = std::string() ); 
void CopyrecoPfMETSigInToOut( std::string prefix = std::string() ); 
void CopytrkMETxPVInToOut( std::string prefix = std::string() ); 
void CopytrkMETyPVInToOut( std::string prefix = std::string() ); 
void CopytrkMETPhiPVInToOut( std::string prefix = std::string() ); 
void CopytrkMETPVInToOut( std::string prefix = std::string() ); 
void CopymetFiltersInToOut( std::string prefix = std::string() ); 
void CopynEleInToOut( std::string prefix = std::string() ); 
void CopyeleTrgInToOut( std::string prefix = std::string() ); 
void CopyeleTrgInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleTrg( std::string prefix ); 
void CopyeleIsEcalDrivenInToOut( std::string prefix = std::string() ); 
void CopyeleIsEcalDrivenInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleIsEcalDriven( std::string prefix ); 
void CopyeleChargeInToOut( std::string prefix = std::string() ); 
void CopyeleChargeInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleCharge( std::string prefix ); 
void CopyeleChargeConsistentInToOut( std::string prefix = std::string() ); 
void CopyeleChargeConsistentInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleChargeConsistent( std::string prefix ); 
void CopyeleEnInToOut( std::string prefix = std::string() ); 
void CopyeleEnInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleEn( std::string prefix ); 
void CopyeleSCEnInToOut( std::string prefix = std::string() ); 
void CopyeleSCEnInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleSCEn( std::string prefix ); 
void CopyelePtInToOut( std::string prefix = std::string() ); 
void CopyelePtInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputelePt( std::string prefix ); 
void CopyeleEtaInToOut( std::string prefix = std::string() ); 
void CopyeleEtaInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleEta( std::string prefix ); 
void CopyelePhiInToOut( std::string prefix = std::string() ); 
void CopyelePhiInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputelePhi( std::string prefix ); 
void CopyeleR9InToOut( std::string prefix = std::string() ); 
void CopyeleR9InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleR9( std::string prefix ); 
void CopyeleSCEtaInToOut( std::string prefix = std::string() ); 
void CopyeleSCEtaInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleSCEta( std::string prefix ); 
void CopyeleSCPhiInToOut( std::string prefix = std::string() ); 
void CopyeleSCPhiInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleSCPhi( std::string prefix ); 
void CopyeleSCEtaWidthInToOut( std::string prefix = std::string() ); 
void CopyeleSCEtaWidthInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleSCEtaWidth( std::string prefix ); 
void CopyeleSCPhiWidthInToOut( std::string prefix = std::string() ); 
void CopyeleSCPhiWidthInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleSCPhiWidth( std::string prefix ); 
void CopyeleVtx_xInToOut( std::string prefix = std::string() ); 
void CopyeleVtx_xInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleVtx_x( std::string prefix ); 
void CopyeleVtx_yInToOut( std::string prefix = std::string() ); 
void CopyeleVtx_yInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleVtx_y( std::string prefix ); 
void CopyeleVtx_zInToOut( std::string prefix = std::string() ); 
void CopyeleVtx_zInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleVtx_z( std::string prefix ); 
void CopyeleD0InToOut( std::string prefix = std::string() ); 
void CopyeleD0InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleD0( std::string prefix ); 
void CopyeleDzInToOut( std::string prefix = std::string() ); 
void CopyeleDzInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleDz( std::string prefix ); 
void CopyeleD0GVInToOut( std::string prefix = std::string() ); 
void CopyeleD0GVInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleD0GV( std::string prefix ); 
void CopyeleDzGVInToOut( std::string prefix = std::string() ); 
void CopyeleDzGVInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleDzGV( std::string prefix ); 
void CopyeleD0VtxInToOut( std::string prefix = std::string() ); 
void CopyeleD0VtxInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleD0Vtx( std::string prefix ); 
void CopyeleDzVtxInToOut( std::string prefix = std::string() ); 
void CopyeleDzVtxInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleDzVtx( std::string prefix ); 
void CopyeleHoverEInToOut( std::string prefix = std::string() ); 
void CopyeleHoverEInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleHoverE( std::string prefix ); 
void CopyeleHoverE12InToOut( std::string prefix = std::string() ); 
void CopyeleHoverE12InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleHoverE12( std::string prefix ); 
void CopyeleEoverPInToOut( std::string prefix = std::string() ); 
void CopyeleEoverPInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleEoverP( std::string prefix ); 
void CopyeledEtaAtVtxInToOut( std::string prefix = std::string() ); 
void CopyeledEtaAtVtxInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeledEtaAtVtx( std::string prefix ); 
void CopyeledPhiAtVtxInToOut( std::string prefix = std::string() ); 
void CopyeledPhiAtVtxInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeledPhiAtVtx( std::string prefix ); 
void CopyeleSigmaIEtaIEtaInToOut( std::string prefix = std::string() ); 
void CopyeleSigmaIEtaIEtaInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleSigmaIEtaIEta( std::string prefix ); 
void CopyeleSigmaIEtaIPhiInToOut( std::string prefix = std::string() ); 
void CopyeleSigmaIEtaIPhiInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleSigmaIEtaIPhi( std::string prefix ); 
void CopyeleSigmaIPhiIPhiInToOut( std::string prefix = std::string() ); 
void CopyeleSigmaIPhiIPhiInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleSigmaIPhiIPhi( std::string prefix ); 
void CopyeleEmaxInToOut( std::string prefix = std::string() ); 
void CopyeleEmaxInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleEmax( std::string prefix ); 
void CopyeleE2ndMaxInToOut( std::string prefix = std::string() ); 
void CopyeleE2ndMaxInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleE2ndMax( std::string prefix ); 
void CopyeleE1x5InToOut( std::string prefix = std::string() ); 
void CopyeleE1x5InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleE1x5( std::string prefix ); 
void CopyeleE3x3InToOut( std::string prefix = std::string() ); 
void CopyeleE3x3InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleE3x3( std::string prefix ); 
void CopyeleE5x5InToOut( std::string prefix = std::string() ); 
void CopyeleE5x5InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleE5x5( std::string prefix ); 
void CopyeleE2x5MaxInToOut( std::string prefix = std::string() ); 
void CopyeleE2x5MaxInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleE2x5Max( std::string prefix ); 
void CopyeleGSFPtInToOut( std::string prefix = std::string() ); 
void CopyeleGSFPtInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleGSFPt( std::string prefix ); 
void CopyeleGSFEtaInToOut( std::string prefix = std::string() ); 
void CopyeleGSFEtaInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleGSFEta( std::string prefix ); 
void CopyeleGSFPhiInToOut( std::string prefix = std::string() ); 
void CopyeleGSFPhiInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleGSFPhi( std::string prefix ); 
void CopyeleGSFChargeInToOut( std::string prefix = std::string() ); 
void CopyeleGSFChargeInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleGSFCharge( std::string prefix ); 
void CopyeleGSFChi2NDFInToOut( std::string prefix = std::string() ); 
void CopyeleGSFChi2NDFInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleGSFChi2NDF( std::string prefix ); 
void CopyeleRecoFlagInToOut( std::string prefix = std::string() ); 
void CopyeleRecoFlagInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleRecoFlag( std::string prefix ); 
void CopyelePosInToOut( std::string prefix = std::string() ); 
void CopyelePosInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputelePos( std::string prefix ); 
void CopyeleIsoTrkDR03InToOut( std::string prefix = std::string() ); 
void CopyeleIsoTrkDR03InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleIsoTrkDR03( std::string prefix ); 
void CopyeleIsoEcalDR03InToOut( std::string prefix = std::string() ); 
void CopyeleIsoEcalDR03InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleIsoEcalDR03( std::string prefix ); 
void CopyeleIsoHcalDR03InToOut( std::string prefix = std::string() ); 
void CopyeleIsoHcalDR03InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleIsoHcalDR03( std::string prefix ); 
void CopyeleIsoHcalDR0312InToOut( std::string prefix = std::string() ); 
void CopyeleIsoHcalDR0312InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleIsoHcalDR0312( std::string prefix ); 
void CopyeleIsoTrkDR04InToOut( std::string prefix = std::string() ); 
void CopyeleIsoTrkDR04InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleIsoTrkDR04( std::string prefix ); 
void CopyeleIsoEcalDR04InToOut( std::string prefix = std::string() ); 
void CopyeleIsoEcalDR04InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleIsoEcalDR04( std::string prefix ); 
void CopyeleIsoHcalDR04InToOut( std::string prefix = std::string() ); 
void CopyeleIsoHcalDR04InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleIsoHcalDR04( std::string prefix ); 
void CopyeleIsoHcalDR0412InToOut( std::string prefix = std::string() ); 
void CopyeleIsoHcalDR0412InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleIsoHcalDR0412( std::string prefix ); 
void CopyeleMissHitsInToOut( std::string prefix = std::string() ); 
void CopyeleMissHitsInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleMissHits( std::string prefix ); 
void CopyeleConvDistInToOut( std::string prefix = std::string() ); 
void CopyeleConvDistInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleConvDist( std::string prefix ); 
void CopyeleConvVtxFitInToOut( std::string prefix = std::string() ); 
void CopyeleConvVtxFitInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleConvVtxFit( std::string prefix ); 
void CopyeleIP3DInToOut( std::string prefix = std::string() ); 
void CopyeleIP3DInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleIP3D( std::string prefix ); 
void CopyeleIP3DErrInToOut( std::string prefix = std::string() ); 
void CopyeleIP3DErrInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleIP3DErr( std::string prefix ); 
void CopyeleIDMVANonTrigInToOut( std::string prefix = std::string() ); 
void CopyeleIDMVANonTrigInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleIDMVANonTrig( std::string prefix ); 
void CopyeleIDMVATrigInToOut( std::string prefix = std::string() ); 
void CopyeleIDMVATrigInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputeleIDMVATrig( std::string prefix ); 
void CopyelePFChIso03InToOut( std::string prefix = std::string() ); 
void CopyelePFChIso03InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputelePFChIso03( std::string prefix ); 
void CopyelePFPhoIso03InToOut( std::string prefix = std::string() ); 
void CopyelePFPhoIso03InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputelePFPhoIso03( std::string prefix ); 
void CopyelePFNeuIso03InToOut( std::string prefix = std::string() ); 
void CopyelePFNeuIso03InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputelePFNeuIso03( std::string prefix ); 
void CopyelePFChIso04InToOut( std::string prefix = std::string() ); 
void CopyelePFChIso04InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputelePFChIso04( std::string prefix ); 
void CopyelePFPhoIso04InToOut( std::string prefix = std::string() ); 
void CopyelePFPhoIso04InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputelePFPhoIso04( std::string prefix ); 
void CopyelePFNeuIso04InToOut( std::string prefix = std::string() ); 
void CopyelePFNeuIso04InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputelePFNeuIso04( std::string prefix ); 
void CopynPhoInToOut( std::string prefix = std::string() ); 
void CopyphoTrgInToOut( std::string prefix = std::string() ); 
void CopyphoTrgInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoTrg( std::string prefix ); 
void CopyphoTrgFilterInToOut( std::string prefix = std::string() ); 
void CopyphoTrgFilterInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoTrgFilter( std::string prefix ); 
void CopyphoIsPhotonInToOut( std::string prefix = std::string() ); 
void CopyphoIsPhotonInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoIsPhoton( std::string prefix ); 
void CopyphoEInToOut( std::string prefix = std::string() ); 
void CopyphoEInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoE( std::string prefix ); 
void CopyphoEtInToOut( std::string prefix = std::string() ); 
void CopyphoEtInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoEt( std::string prefix ); 
void CopyphoEtaInToOut( std::string prefix = std::string() ); 
void CopyphoEtaInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoEta( std::string prefix ); 
void CopyphoVtx_xInToOut( std::string prefix = std::string() ); 
void CopyphoVtx_xInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoVtx_x( std::string prefix ); 
void CopyphoVtx_yInToOut( std::string prefix = std::string() ); 
void CopyphoVtx_yInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoVtx_y( std::string prefix ); 
void CopyphoVtx_zInToOut( std::string prefix = std::string() ); 
void CopyphoVtx_zInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoVtx_z( std::string prefix ); 
void CopyphoPhiInToOut( std::string prefix = std::string() ); 
void CopyphoPhiInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoPhi( std::string prefix ); 
void CopyphoR9InToOut( std::string prefix = std::string() ); 
void CopyphoR9InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoR9( std::string prefix ); 
void CopyphoNClusInToOut( std::string prefix = std::string() ); 
void CopyphoNClusInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoNClus( std::string prefix ); 
void CopyphoTrkIsoHollowDR03InToOut( std::string prefix = std::string() ); 
void CopyphoTrkIsoHollowDR03InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoTrkIsoHollowDR03( std::string prefix ); 
void CopyphoEcalIsoDR03InToOut( std::string prefix = std::string() ); 
void CopyphoEcalIsoDR03InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoEcalIsoDR03( std::string prefix ); 
void CopyphoHcalIsoDR03InToOut( std::string prefix = std::string() ); 
void CopyphoHcalIsoDR03InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoHcalIsoDR03( std::string prefix ); 
void CopyphoHcalIsoDR0312InToOut( std::string prefix = std::string() ); 
void CopyphoHcalIsoDR0312InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoHcalIsoDR0312( std::string prefix ); 
void CopyphoTrkIsoHollowDR04InToOut( std::string prefix = std::string() ); 
void CopyphoTrkIsoHollowDR04InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoTrkIsoHollowDR04( std::string prefix ); 
void CopyphoCiCdRtoTrkInToOut( std::string prefix = std::string() ); 
void CopyphoCiCdRtoTrkInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoCiCdRtoTrk( std::string prefix ); 
void CopyphoEcalIsoDR04InToOut( std::string prefix = std::string() ); 
void CopyphoEcalIsoDR04InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoEcalIsoDR04( std::string prefix ); 
void CopyphoHcalIsoDR04InToOut( std::string prefix = std::string() ); 
void CopyphoHcalIsoDR04InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoHcalIsoDR04( std::string prefix ); 
void CopyphoHoverEInToOut( std::string prefix = std::string() ); 
void CopyphoHoverEInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoHoverE( std::string prefix ); 
void CopyphoHoverE12InToOut( std::string prefix = std::string() ); 
void CopyphoHoverE12InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoHoverE12( std::string prefix ); 
void CopyphoEleVetoInToOut( std::string prefix = std::string() ); 
void CopyphoEleVetoInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoEleVeto( std::string prefix ); 
void CopyphoSigmaIEtaIEtaInToOut( std::string prefix = std::string() ); 
void CopyphoSigmaIEtaIEtaInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoSigmaIEtaIEta( std::string prefix ); 
void CopyphoSigmaIEtaIPhiInToOut( std::string prefix = std::string() ); 
void CopyphoSigmaIEtaIPhiInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoSigmaIEtaIPhi( std::string prefix ); 
void CopyphoSigmaIPhiIPhiInToOut( std::string prefix = std::string() ); 
void CopyphoSigmaIPhiIPhiInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoSigmaIPhiIPhi( std::string prefix ); 
void CopyphoCiCPF4phopfIso03InToOut( std::string prefix = std::string() ); 
void CopyphoCiCPF4phopfIso03InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoCiCPF4phopfIso03( std::string prefix ); 
void CopyphoEmaxInToOut( std::string prefix = std::string() ); 
void CopyphoEmaxInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoEmax( std::string prefix ); 
void CopyphoE2ndMaxInToOut( std::string prefix = std::string() ); 
void CopyphoE2ndMaxInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoE2ndMax( std::string prefix ); 
void CopyphoE3x3InToOut( std::string prefix = std::string() ); 
void CopyphoE3x3InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoE3x3( std::string prefix ); 
void CopyphoE3x1InToOut( std::string prefix = std::string() ); 
void CopyphoE3x1InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoE3x1( std::string prefix ); 
void CopyphoE1x3InToOut( std::string prefix = std::string() ); 
void CopyphoE1x3InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoE1x3( std::string prefix ); 
void CopyphoE5x5InToOut( std::string prefix = std::string() ); 
void CopyphoE5x5InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoE5x5( std::string prefix ); 
void CopyphoE1x5InToOut( std::string prefix = std::string() ); 
void CopyphoE1x5InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoE1x5( std::string prefix ); 
void CopyphoE2x2InToOut( std::string prefix = std::string() ); 
void CopyphoE2x2InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoE2x2( std::string prefix ); 
void CopyphoE2x5MaxInToOut( std::string prefix = std::string() ); 
void CopyphoE2x5MaxInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoE2x5Max( std::string prefix ); 
void CopyphoPFChIsoInToOut( std::string prefix = std::string() ); 
void CopyphoPFChIsoInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoPFChIso( std::string prefix ); 
void CopyphoPFPhoIsoInToOut( std::string prefix = std::string() ); 
void CopyphoPFPhoIsoInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoPFPhoIso( std::string prefix ); 
void CopyphoPFNeuIsoInToOut( std::string prefix = std::string() ); 
void CopyphoPFNeuIsoInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoPFNeuIso( std::string prefix ); 
void CopyphoSCRChIsoInToOut( std::string prefix = std::string() ); 
void CopyphoSCRChIsoInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoSCRChIso( std::string prefix ); 
void CopyphoSCRNeuIsoInToOut( std::string prefix = std::string() ); 
void CopyphoSCRNeuIsoInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoSCRNeuIso( std::string prefix ); 
void CopyphoSCRChIso04InToOut( std::string prefix = std::string() ); 
void CopyphoSCRChIso04InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoSCRChIso04( std::string prefix ); 
void CopyphoSCRPhoIso04InToOut( std::string prefix = std::string() ); 
void CopyphoSCRPhoIso04InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoSCRPhoIso04( std::string prefix ); 
void CopyphoSCRNeuIso04InToOut( std::string prefix = std::string() ); 
void CopyphoSCRNeuIso04InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoSCRNeuIso04( std::string prefix ); 
void CopyphoRandConeChIsoInToOut( std::string prefix = std::string() ); 
void CopyphoRandConeChIsoInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoRandConeChIso( std::string prefix ); 
void CopyphoRandConePhoIsoInToOut( std::string prefix = std::string() ); 
void CopyphoRandConePhoIsoInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoRandConePhoIso( std::string prefix ); 
void CopyphoRandConeNeuIsoInToOut( std::string prefix = std::string() ); 
void CopyphoRandConeNeuIsoInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoRandConeNeuIso( std::string prefix ); 
void CopyphoRandConeChIso04InToOut( std::string prefix = std::string() ); 
void CopyphoRandConeChIso04InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoRandConeChIso04( std::string prefix ); 
void CopyphoRandConePhoIso04InToOut( std::string prefix = std::string() ); 
void CopyphoRandConePhoIso04InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoRandConePhoIso04( std::string prefix ); 
void CopyphoRandConeNeuIso04InToOut( std::string prefix = std::string() ); 
void CopyphoRandConeNeuIso04InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoRandConeNeuIso04( std::string prefix ); 
void CopyphoRecoFlagInToOut( std::string prefix = std::string() ); 
void CopyphoRecoFlagInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoRecoFlag( std::string prefix ); 
void CopyphoPosInToOut( std::string prefix = std::string() ); 
void CopyphoPosInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoPos( std::string prefix ); 
void CopyphoSCEInToOut( std::string prefix = std::string() ); 
void CopyphoSCEInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoSCE( std::string prefix ); 
void CopyphoSCRawEInToOut( std::string prefix = std::string() ); 
void CopyphoSCRawEInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoSCRawE( std::string prefix ); 
void CopyphoESEnInToOut( std::string prefix = std::string() ); 
void CopyphoESEnInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoESEn( std::string prefix ); 
void CopyphoSCEtInToOut( std::string prefix = std::string() ); 
void CopyphoSCEtInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoSCEt( std::string prefix ); 
void CopyphoSCEtaInToOut( std::string prefix = std::string() ); 
void CopyphoSCEtaInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoSCEta( std::string prefix ); 
void CopyphoSCPhiInToOut( std::string prefix = std::string() ); 
void CopyphoSCPhiInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoSCPhi( std::string prefix ); 
void CopyphoSCEtaWidthInToOut( std::string prefix = std::string() ); 
void CopyphoSCEtaWidthInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoSCEtaWidth( std::string prefix ); 
void CopyphoSCPhiWidthInToOut( std::string prefix = std::string() ); 
void CopyphoSCPhiWidthInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoSCPhiWidth( std::string prefix ); 
void CopyphoOverlapInToOut( std::string prefix = std::string() ); 
void CopyphoOverlapInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoOverlap( std::string prefix ); 
void CopyphohasPixelSeedInToOut( std::string prefix = std::string() ); 
void CopyphohasPixelSeedInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphohasPixelSeed( std::string prefix ); 
void Copypho_hasConvPfInToOut( std::string prefix = std::string() ); 
void Copypho_hasConvPfInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputpho_hasConvPf( std::string prefix ); 
void Copypho_hasSLConvPfInToOut( std::string prefix = std::string() ); 
void Copypho_hasSLConvPfInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputpho_hasSLConvPf( std::string prefix ); 
void Copypho_pfconvVtxZInToOut( std::string prefix = std::string() ); 
void Copypho_pfconvVtxZInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputpho_pfconvVtxZ( std::string prefix ); 
void Copypho_pfconvVtxZErrInToOut( std::string prefix = std::string() ); 
void Copypho_pfconvVtxZErrInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputpho_pfconvVtxZErr( std::string prefix ); 
void Copypho_nSLConvInToOut( std::string prefix = std::string() ); 
void Copypho_nSLConvInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputpho_nSLConv( std::string prefix ); 
void Copypho_pfSLConvPos_xInToOut( std::string prefix = std::string() ); 
void Copypho_pfSLConvPos_xInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputpho_pfSLConvPos_x( std::string prefix ); 
void Copypho_pfSLConvPos_yInToOut( std::string prefix = std::string() ); 
void Copypho_pfSLConvPos_yInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputpho_pfSLConvPos_y( std::string prefix ); 
void Copypho_pfSLConvPos_zInToOut( std::string prefix = std::string() ); 
void Copypho_pfSLConvPos_zInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputpho_pfSLConvPos_z( std::string prefix ); 
void Copypho_pfSLConvVtxZInToOut( std::string prefix = std::string() ); 
void Copypho_pfSLConvVtxZInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputpho_pfSLConvVtxZ( std::string prefix ); 
void CopyphoIsConvInToOut( std::string prefix = std::string() ); 
void CopyphoIsConvInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoIsConv( std::string prefix ); 
void CopyphoNConvInToOut( std::string prefix = std::string() ); 
void CopyphoNConvInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoNConv( std::string prefix ); 
void CopyphoConvInvMassInToOut( std::string prefix = std::string() ); 
void CopyphoConvInvMassInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoConvInvMass( std::string prefix ); 
void CopyphoConvCotThetaInToOut( std::string prefix = std::string() ); 
void CopyphoConvCotThetaInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoConvCotTheta( std::string prefix ); 
void CopyphoConvEoverPInToOut( std::string prefix = std::string() ); 
void CopyphoConvEoverPInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoConvEoverP( std::string prefix ); 
void CopyphoConvMinDistInToOut( std::string prefix = std::string() ); 
void CopyphoConvMinDistInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoConvMinDist( std::string prefix ); 
void CopyphoConvdPhiAtVtxInToOut( std::string prefix = std::string() ); 
void CopyphoConvdPhiAtVtxInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoConvdPhiAtVtx( std::string prefix ); 
void CopyphoConvdPhiAtCaloInToOut( std::string prefix = std::string() ); 
void CopyphoConvdPhiAtCaloInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoConvdPhiAtCalo( std::string prefix ); 
void CopyphoConvdEtaAtCaloInToOut( std::string prefix = std::string() ); 
void CopyphoConvdEtaAtCaloInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoConvdEtaAtCalo( std::string prefix ); 
void CopyphoConvTrkPin_xInToOut( std::string prefix = std::string() ); 
void CopyphoConvTrkPin_xInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoConvTrkPin_x( std::string prefix ); 
void CopyphoConvTrkPin_yInToOut( std::string prefix = std::string() ); 
void CopyphoConvTrkPin_yInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoConvTrkPin_y( std::string prefix ); 
void CopyphoConvTrkPout_xInToOut( std::string prefix = std::string() ); 
void CopyphoConvTrkPout_xInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoConvTrkPout_x( std::string prefix ); 
void CopyphoConvTrkPout_yInToOut( std::string prefix = std::string() ); 
void CopyphoConvTrkPout_yInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoConvTrkPout_y( std::string prefix ); 
void CopyphoConvChi2InToOut( std::string prefix = std::string() ); 
void CopyphoConvChi2InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoConvChi2( std::string prefix ); 
void CopyphoConvChi2ProbInToOut( std::string prefix = std::string() ); 
void CopyphoConvChi2ProbInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoConvChi2Prob( std::string prefix ); 
void CopyphoConvNTrksInToOut( std::string prefix = std::string() ); 
void CopyphoConvNTrksInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoConvNTrks( std::string prefix ); 
void CopyphoConvVtx_xInToOut( std::string prefix = std::string() ); 
void CopyphoConvVtx_xInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoConvVtx_x( std::string prefix ); 
void CopyphoConvVtx_yInToOut( std::string prefix = std::string() ); 
void CopyphoConvVtx_yInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoConvVtx_y( std::string prefix ); 
void CopyphoConvVtx_zInToOut( std::string prefix = std::string() ); 
void CopyphoConvVtx_zInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoConvVtx_z( std::string prefix ); 
void CopyphoConvPairMomentum_xInToOut( std::string prefix = std::string() ); 
void CopyphoConvPairMomentum_xInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoConvPairMomentum_x( std::string prefix ); 
void CopyphoConvPairMomentum_yInToOut( std::string prefix = std::string() ); 
void CopyphoConvPairMomentum_yInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoConvPairMomentum_y( std::string prefix ); 
void CopyphoConvPairMomentum_zInToOut( std::string prefix = std::string() ); 
void CopyphoConvPairMomentum_zInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoConvPairMomentum_z( std::string prefix ); 
void CopySingleLegConvInToOut( std::string prefix = std::string() ); 
void CopySingleLegConvInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputSingleLegConv( std::string prefix ); 
void CopyphoPFConvVtx_xInToOut( std::string prefix = std::string() ); 
void CopyphoPFConvVtx_xInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoPFConvVtx_x( std::string prefix ); 
void CopyphoPFConvVtx_yInToOut( std::string prefix = std::string() ); 
void CopyphoPFConvVtx_yInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoPFConvVtx_y( std::string prefix ); 
void CopyphoPFConvVtx_zInToOut( std::string prefix = std::string() ); 
void CopyphoPFConvVtx_zInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoPFConvVtx_z( std::string prefix ); 
void CopyphoPFConvMom_xInToOut( std::string prefix = std::string() ); 
void CopyphoPFConvMom_xInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoPFConvMom_x( std::string prefix ); 
void CopyphoPFConvMom_yInToOut( std::string prefix = std::string() ); 
void CopyphoPFConvMom_yInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoPFConvMom_y( std::string prefix ); 
void CopyphoPFConvMom_zInToOut( std::string prefix = std::string() ); 
void CopyphoPFConvMom_zInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputphoPFConvMom_z( std::string prefix ); 
void CopynMuInToOut( std::string prefix = std::string() ); 
void CopymuTrgInToOut( std::string prefix = std::string() ); 
void CopymuTrgInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuTrg( std::string prefix ); 
void CopymuEtaInToOut( std::string prefix = std::string() ); 
void CopymuEtaInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuEta( std::string prefix ); 
void CopymuPhiInToOut( std::string prefix = std::string() ); 
void CopymuPhiInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuPhi( std::string prefix ); 
void CopymuChargeInToOut( std::string prefix = std::string() ); 
void CopymuChargeInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuCharge( std::string prefix ); 
void CopymuPtInToOut( std::string prefix = std::string() ); 
void CopymuPtInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuPt( std::string prefix ); 
void CopymuPzInToOut( std::string prefix = std::string() ); 
void CopymuPzInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuPz( std::string prefix ); 
void CopymuVtx_xInToOut( std::string prefix = std::string() ); 
void CopymuVtx_xInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuVtx_x( std::string prefix ); 
void CopymuVtx_yInToOut( std::string prefix = std::string() ); 
void CopymuVtx_yInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuVtx_y( std::string prefix ); 
void CopymuVtx_zInToOut( std::string prefix = std::string() ); 
void CopymuVtx_zInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuVtx_z( std::string prefix ); 
void CopymuIsoTrkInToOut( std::string prefix = std::string() ); 
void CopymuIsoTrkInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuIsoTrk( std::string prefix ); 
void CopymuIsoCaloInToOut( std::string prefix = std::string() ); 
void CopymuIsoCaloInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuIsoCalo( std::string prefix ); 
void CopymuIsoEcalInToOut( std::string prefix = std::string() ); 
void CopymuIsoEcalInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuIsoEcal( std::string prefix ); 
void CopymuIsoHcalInToOut( std::string prefix = std::string() ); 
void CopymuIsoHcalInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuIsoHcal( std::string prefix ); 
void CopymuChi2NDFInToOut( std::string prefix = std::string() ); 
void CopymuChi2NDFInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuChi2NDF( std::string prefix ); 
void CopymuInnerChi2NDFInToOut( std::string prefix = std::string() ); 
void CopymuInnerChi2NDFInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuInnerChi2NDF( std::string prefix ); 
void CopymuPFIsoR04_CHInToOut( std::string prefix = std::string() ); 
void CopymuPFIsoR04_CHInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuPFIsoR04_CH( std::string prefix ); 
void CopymuPFIsoR04_NHInToOut( std::string prefix = std::string() ); 
void CopymuPFIsoR04_NHInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuPFIsoR04_NH( std::string prefix ); 
void CopymuPFIsoR04_PhoInToOut( std::string prefix = std::string() ); 
void CopymuPFIsoR04_PhoInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuPFIsoR04_Pho( std::string prefix ); 
void CopymuPFIsoR04_PUInToOut( std::string prefix = std::string() ); 
void CopymuPFIsoR04_PUInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuPFIsoR04_PU( std::string prefix ); 
void CopymuPFIsoR04_CPartInToOut( std::string prefix = std::string() ); 
void CopymuPFIsoR04_CPartInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuPFIsoR04_CPart( std::string prefix ); 
void CopymuPFIsoR04_NHHTInToOut( std::string prefix = std::string() ); 
void CopymuPFIsoR04_NHHTInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuPFIsoR04_NHHT( std::string prefix ); 
void CopymuPFIsoR04_PhoHTInToOut( std::string prefix = std::string() ); 
void CopymuPFIsoR04_PhoHTInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuPFIsoR04_PhoHT( std::string prefix ); 
void CopymuPFIsoR03_CHInToOut( std::string prefix = std::string() ); 
void CopymuPFIsoR03_CHInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuPFIsoR03_CH( std::string prefix ); 
void CopymuPFIsoR03_NHInToOut( std::string prefix = std::string() ); 
void CopymuPFIsoR03_NHInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuPFIsoR03_NH( std::string prefix ); 
void CopymuPFIsoR03_PhoInToOut( std::string prefix = std::string() ); 
void CopymuPFIsoR03_PhoInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuPFIsoR03_Pho( std::string prefix ); 
void CopymuPFIsoR03_PUInToOut( std::string prefix = std::string() ); 
void CopymuPFIsoR03_PUInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuPFIsoR03_PU( std::string prefix ); 
void CopymuPFIsoR03_CPartInToOut( std::string prefix = std::string() ); 
void CopymuPFIsoR03_CPartInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuPFIsoR03_CPart( std::string prefix ); 
void CopymuPFIsoR03_NHHTInToOut( std::string prefix = std::string() ); 
void CopymuPFIsoR03_NHHTInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuPFIsoR03_NHHT( std::string prefix ); 
void CopymuPFIsoR03_PhoHTInToOut( std::string prefix = std::string() ); 
void CopymuPFIsoR03_PhoHTInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuPFIsoR03_PhoHT( std::string prefix ); 
void CopymuTypeInToOut( std::string prefix = std::string() ); 
void CopymuTypeInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuType( std::string prefix ); 
void CopymuD0InToOut( std::string prefix = std::string() ); 
void CopymuD0InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuD0( std::string prefix ); 
void CopymuDzInToOut( std::string prefix = std::string() ); 
void CopymuDzInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuDz( std::string prefix ); 
void CopymuD0GVInToOut( std::string prefix = std::string() ); 
void CopymuD0GVInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuD0GV( std::string prefix ); 
void CopymuDzGVInToOut( std::string prefix = std::string() ); 
void CopymuDzGVInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuDzGV( std::string prefix ); 
void CopymuD0VtxInToOut( std::string prefix = std::string() ); 
void CopymuD0VtxInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuD0Vtx( std::string prefix ); 
void CopymuDzVtxInToOut( std::string prefix = std::string() ); 
void CopymuDzVtxInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuDzVtx( std::string prefix ); 
void CopymuInnerD0InToOut( std::string prefix = std::string() ); 
void CopymuInnerD0InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuInnerD0( std::string prefix ); 
void CopymuInnerDzInToOut( std::string prefix = std::string() ); 
void CopymuInnerDzInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuInnerDz( std::string prefix ); 
void CopymuInnerD0GVInToOut( std::string prefix = std::string() ); 
void CopymuInnerD0GVInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuInnerD0GV( std::string prefix ); 
void CopymuInnerDzGVInToOut( std::string prefix = std::string() ); 
void CopymuInnerDzGVInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuInnerDzGV( std::string prefix ); 
void CopymuInnerPtInToOut( std::string prefix = std::string() ); 
void CopymuInnerPtInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuInnerPt( std::string prefix ); 
void CopymuNumberOfValidTrkLayersInToOut( std::string prefix = std::string() ); 
void CopymuNumberOfValidTrkLayersInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuNumberOfValidTrkLayers( std::string prefix ); 
void CopymuNumberOfValidTrkHitsInToOut( std::string prefix = std::string() ); 
void CopymuNumberOfValidTrkHitsInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuNumberOfValidTrkHits( std::string prefix ); 
void CopymuNumberOfValidPixelLayersInToOut( std::string prefix = std::string() ); 
void CopymuNumberOfValidPixelLayersInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuNumberOfValidPixelLayers( std::string prefix ); 
void CopymuNumberOfValidPixelHitsInToOut( std::string prefix = std::string() ); 
void CopymuNumberOfValidPixelHitsInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuNumberOfValidPixelHits( std::string prefix ); 
void CopymuNumberOfValidMuonHitsInToOut( std::string prefix = std::string() ); 
void CopymuNumberOfValidMuonHitsInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuNumberOfValidMuonHits( std::string prefix ); 
void CopymuStationsInToOut( std::string prefix = std::string() ); 
void CopymuStationsInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuStations( std::string prefix ); 
void CopymuChambersInToOut( std::string prefix = std::string() ); 
void CopymuChambersInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuChambers( std::string prefix ); 
void CopymuIP3DInToOut( std::string prefix = std::string() ); 
void CopymuIP3DInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuIP3D( std::string prefix ); 
void CopymuIP3DErrInToOut( std::string prefix = std::string() ); 
void CopymuIP3DErrInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmuIP3DErr( std::string prefix ); 
void CopynTauInToOut( std::string prefix = std::string() ); 
void Copyrho25InToOut( std::string prefix = std::string() ); 
void Copyrho25_neuInToOut( std::string prefix = std::string() ); 
void Copyrho25_muPFisoInToOut( std::string prefix = std::string() ); 
void Copyrho25_elePFisoInToOut( std::string prefix = std::string() ); 
void Copyrho2011InToOut( std::string prefix = std::string() ); 
void Copyrho2012InToOut( std::string prefix = std::string() ); 
void CopyQGTag_MLPInToOut( std::string prefix = std::string() ); 
void CopyQGTag_likelihoodInToOut( std::string prefix = std::string() ); 
void CopynCA8JetInToOut( std::string prefix = std::string() ); 
void CopynJetInToOut( std::string prefix = std::string() ); 
void CopyjetTrgInToOut( std::string prefix = std::string() ); 
void CopyjetTrgInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputjetTrg( std::string prefix ); 
void CopyjetEnInToOut( std::string prefix = std::string() ); 
void CopyjetEnInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputjetEn( std::string prefix ); 
void CopyjetPtInToOut( std::string prefix = std::string() ); 
void CopyjetPtInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputjetPt( std::string prefix ); 
void CopyjetEtaInToOut( std::string prefix = std::string() ); 
void CopyjetEtaInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputjetEta( std::string prefix ); 
void CopyjetPhiInToOut( std::string prefix = std::string() ); 
void CopyjetPhiInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputjetPhi( std::string prefix ); 
void CopyjetChargeInToOut( std::string prefix = std::string() ); 
void CopyjetChargeInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputjetCharge( std::string prefix ); 
void CopyjetEtInToOut( std::string prefix = std::string() ); 
void CopyjetEtInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputjetEt( std::string prefix ); 
void CopyjetRawEnInToOut( std::string prefix = std::string() ); 
void CopyjetRawEnInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputjetRawEn( std::string prefix ); 
void CopyjetCHFInToOut( std::string prefix = std::string() ); 
void CopyjetCHFInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputjetCHF( std::string prefix ); 
void CopyjetNHFInToOut( std::string prefix = std::string() ); 
void CopyjetNHFInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputjetNHF( std::string prefix ); 
void CopyjetNEFInToOut( std::string prefix = std::string() ); 
void CopyjetNEFInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputjetNEF( std::string prefix ); 
void CopyjetNCHInToOut( std::string prefix = std::string() ); 
void CopyjetNCHInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputjetNCH( std::string prefix ); 
void CopyjetNConstituentsInToOut( std::string prefix = std::string() ); 
void CopyjetNConstituentsInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputjetNConstituents( std::string prefix ); 
void CopyjetNNeutralsInToOut( std::string prefix = std::string() ); 
void CopyjetNNeutralsInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputjetNNeutrals( std::string prefix ); 
void CopyjetNChargedInToOut( std::string prefix = std::string() ); 
void CopyjetNChargedInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputjetNCharged( std::string prefix ); 
void CopyjetLeadTrackPtInToOut( std::string prefix = std::string() ); 
void CopyjetLeadTrackPtInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputjetLeadTrackPt( std::string prefix ); 
void CopyjetVtxPtInToOut( std::string prefix = std::string() ); 
void CopyjetVtxPtInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputjetVtxPt( std::string prefix ); 
void CopynLowPtJetInToOut( std::string prefix = std::string() ); 
void CopynConvInToOut( std::string prefix = std::string() ); 
#endif
