#ifndef BRANCHINIT_H
#define BRANCHINIT_H
#include "TTree.h"
#include "TChain.h"
void InitINTree( TChain * tree );
void InitOUTTree( TTree * tree );
void CopyInputVarsToOutput(std::string prefix = std::string() );
void CopyPrefixBranchesInToOut( const std::string & prefix );
void CopyPrefixIndexBranchesInToOut( const std::string & prefix, unsigned index );
void ClearOutputPrefix ( const std::string & prefix );
void CopynVtxInToOut( std::string prefix = std::string() ); 
void CopynVtxBSInToOut( std::string prefix = std::string() ); 
void CopynMCInToOut( std::string prefix = std::string() ); 
void CopymcPIDInToOut( std::string prefix = std::string() ); 
void CopymcPIDInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcPID( std::string prefix ); 
void CopymcPtInToOut( std::string prefix = std::string() ); 
void CopymcPtInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcPt( std::string prefix ); 
void CopymcEtaInToOut( std::string prefix = std::string() ); 
void CopymcEtaInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcEta( std::string prefix ); 
void CopymcPhiInToOut( std::string prefix = std::string() ); 
void CopymcPhiInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcPhi( std::string prefix ); 
void CopymcEInToOut( std::string prefix = std::string() ); 
void CopymcEInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcE( std::string prefix ); 
void CopymcGMomPIDInToOut( std::string prefix = std::string() ); 
void CopymcGMomPIDInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcGMomPID( std::string prefix ); 
void CopymcMomPIDInToOut( std::string prefix = std::string() ); 
void CopymcMomPIDInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcMomPID( std::string prefix ); 
void CopymcParentageInToOut( std::string prefix = std::string() ); 
void CopymcParentageInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcParentage( std::string prefix ); 
void CopymcStatusInToOut( std::string prefix = std::string() ); 
void CopymcStatusInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcStatus( std::string prefix ); 
void CopynPUInToOut( std::string prefix = std::string() ); 
void CopynPUInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputnPU( std::string prefix ); 
void CopypuTrueInToOut( std::string prefix = std::string() ); 
void CopypuTrueInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputpuTrue( std::string prefix ); 
void CopypfMETInToOut( std::string prefix = std::string() ); 
void CopypfMETPhiInToOut( std::string prefix = std::string() ); 
void CopypfMETsumEtInToOut( std::string prefix = std::string() ); 
void CopypfMETmEtSigInToOut( std::string prefix = std::string() ); 
void CopypfMETSigInToOut( std::string prefix = std::string() ); 
void CopyrecoPfMETInToOut( std::string prefix = std::string() ); 
void CopyrecoPfMETPhiInToOut( std::string prefix = std::string() ); 
void CopyrecoPfMETsumEtInToOut( std::string prefix = std::string() ); 
void CopyrecoPfMETmEtSigInToOut( std::string prefix = std::string() ); 
void CopyrecoPfMETSigInToOut( std::string prefix = std::string() ); 
void Copyrho2012InToOut( std::string prefix = std::string() ); 
void Copyel_nInToOut( std::string prefix = std::string() ); 
void Copymu_nInToOut( std::string prefix = std::string() ); 
void Copyph_nInToOut( std::string prefix = std::string() ); 
void Copyjet_nInToOut( std::string prefix = std::string() ); 
void Copyvtx_nInToOut( std::string prefix = std::string() ); 
void Copyel_ptInToOut( std::string prefix = std::string() ); 
void Copyel_ptInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputel_pt( std::string prefix ); 
void Copyel_etaInToOut( std::string prefix = std::string() ); 
void Copyel_etaInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputel_eta( std::string prefix ); 
void Copyel_scetaInToOut( std::string prefix = std::string() ); 
void Copyel_scetaInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputel_sceta( std::string prefix ); 
void Copyel_phiInToOut( std::string prefix = std::string() ); 
void Copyel_phiInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputel_phi( std::string prefix ); 
void Copyel_eInToOut( std::string prefix = std::string() ); 
void Copyel_eInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputel_e( std::string prefix ); 
void Copyel_pt_uncorrInToOut( std::string prefix = std::string() ); 
void Copyel_pt_uncorrInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputel_pt_uncorr( std::string prefix ); 
void Copyel_mva_trigInToOut( std::string prefix = std::string() ); 
void Copyel_mva_trigInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputel_mva_trig( std::string prefix ); 
void Copyel_mva_nontrigInToOut( std::string prefix = std::string() ); 
void Copyel_mva_nontrigInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputel_mva_nontrig( std::string prefix ); 
void Copyel_d0pvInToOut( std::string prefix = std::string() ); 
void Copyel_d0pvInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputel_d0pv( std::string prefix ); 
void Copyel_z0pvInToOut( std::string prefix = std::string() ); 
void Copyel_z0pvInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputel_z0pv( std::string prefix ); 
void Copyel_sigmaIEIEInToOut( std::string prefix = std::string() ); 
void Copyel_sigmaIEIEInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputel_sigmaIEIE( std::string prefix ); 
void Copyel_pfiso30InToOut( std::string prefix = std::string() ); 
void Copyel_pfiso30InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputel_pfiso30( std::string prefix ); 
void Copyel_pfiso40InToOut( std::string prefix = std::string() ); 
void Copyel_pfiso40InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputel_pfiso40( std::string prefix ); 
void Copyel_triggerMatchInToOut( std::string prefix = std::string() ); 
void Copyel_triggerMatchInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputel_triggerMatch( std::string prefix ); 
void Copyel_hasMatchedConvInToOut( std::string prefix = std::string() ); 
void Copyel_hasMatchedConvInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputel_hasMatchedConv( std::string prefix ); 
void Copyel_passTightInToOut( std::string prefix = std::string() ); 
void Copyel_passTightInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputel_passTight( std::string prefix ); 
void Copyel_passMediumInToOut( std::string prefix = std::string() ); 
void Copyel_passMediumInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputel_passMedium( std::string prefix ); 
void Copyel_passLooseInToOut( std::string prefix = std::string() ); 
void Copyel_passLooseInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputel_passLoose( std::string prefix ); 
void Copyel_passVeryLooseInToOut( std::string prefix = std::string() ); 
void Copyel_passVeryLooseInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputel_passVeryLoose( std::string prefix ); 
void Copyel_passTightTrigInToOut( std::string prefix = std::string() ); 
void Copyel_passTightTrigInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputel_passTightTrig( std::string prefix ); 
void Copyel_passMvaTrigInToOut( std::string prefix = std::string() ); 
void Copyel_passMvaTrigInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputel_passMvaTrig( std::string prefix ); 
void Copyel_passMvaNonTrigInToOut( std::string prefix = std::string() ); 
void Copyel_passMvaNonTrigInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputel_passMvaNonTrig( std::string prefix ); 
void Copyel_truthMatch_elInToOut( std::string prefix = std::string() ); 
void Copyel_truthMatch_elInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputel_truthMatch_el( std::string prefix ); 
void Copyel_truthMinDR_elInToOut( std::string prefix = std::string() ); 
void Copyel_truthMinDR_elInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputel_truthMinDR_el( std::string prefix ); 
void Copyel_truthMatchPt_elInToOut( std::string prefix = std::string() ); 
void Copyel_truthMatchPt_elInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputel_truthMatchPt_el( std::string prefix ); 
void Copymu_ptInToOut( std::string prefix = std::string() ); 
void Copymu_ptInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmu_pt( std::string prefix ); 
void Copymu_etaInToOut( std::string prefix = std::string() ); 
void Copymu_etaInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmu_eta( std::string prefix ); 
void Copymu_phiInToOut( std::string prefix = std::string() ); 
void Copymu_phiInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmu_phi( std::string prefix ); 
void Copymu_eInToOut( std::string prefix = std::string() ); 
void Copymu_eInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmu_e( std::string prefix ); 
void Copymu_pt_uncorrInToOut( std::string prefix = std::string() ); 
void Copymu_pt_uncorrInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmu_pt_uncorr( std::string prefix ); 
void Copymu_pfIso_chInToOut( std::string prefix = std::string() ); 
void Copymu_pfIso_chInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmu_pfIso_ch( std::string prefix ); 
void Copymu_pfIso_nhInToOut( std::string prefix = std::string() ); 
void Copymu_pfIso_nhInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmu_pfIso_nh( std::string prefix ); 
void Copymu_pfIso_phoInToOut( std::string prefix = std::string() ); 
void Copymu_pfIso_phoInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmu_pfIso_pho( std::string prefix ); 
void Copymu_pfIso_puInToOut( std::string prefix = std::string() ); 
void Copymu_pfIso_puInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmu_pfIso_pu( std::string prefix ); 
void Copymu_corrIsoInToOut( std::string prefix = std::string() ); 
void Copymu_corrIsoInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmu_corrIso( std::string prefix ); 
void Copymu_triggerMatchInToOut( std::string prefix = std::string() ); 
void Copymu_triggerMatchInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmu_triggerMatch( std::string prefix ); 
void Copymu_truthMatchInToOut( std::string prefix = std::string() ); 
void Copymu_truthMatchInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmu_truthMatch( std::string prefix ); 
void Copymu_truthMinDRInToOut( std::string prefix = std::string() ); 
void Copymu_truthMinDRInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmu_truthMinDR( std::string prefix ); 
void Copyph_ptInToOut( std::string prefix = std::string() ); 
void Copyph_ptInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_pt( std::string prefix ); 
void Copyph_etaInToOut( std::string prefix = std::string() ); 
void Copyph_etaInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_eta( std::string prefix ); 
void Copyph_scetaInToOut( std::string prefix = std::string() ); 
void Copyph_scetaInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_sceta( std::string prefix ); 
void Copyph_phiInToOut( std::string prefix = std::string() ); 
void Copyph_phiInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_phi( std::string prefix ); 
void Copyph_eInToOut( std::string prefix = std::string() ); 
void Copyph_eInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_e( std::string prefix ); 
void Copyph_HoverEInToOut( std::string prefix = std::string() ); 
void Copyph_HoverEInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_HoverE( std::string prefix ); 
void Copyph_HoverE12InToOut( std::string prefix = std::string() ); 
void Copyph_HoverE12InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_HoverE12( std::string prefix ); 
void Copyph_sigmaIEIEInToOut( std::string prefix = std::string() ); 
void Copyph_sigmaIEIEInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_sigmaIEIE( std::string prefix ); 
void Copyph_sigmaIEIPInToOut( std::string prefix = std::string() ); 
void Copyph_sigmaIEIPInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_sigmaIEIP( std::string prefix ); 
void Copyph_r9InToOut( std::string prefix = std::string() ); 
void Copyph_r9InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_r9( std::string prefix ); 
void Copyph_E1x3InToOut( std::string prefix = std::string() ); 
void Copyph_E1x3InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_E1x3( std::string prefix ); 
void Copyph_E2x2InToOut( std::string prefix = std::string() ); 
void Copyph_E2x2InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_E2x2( std::string prefix ); 
void Copyph_E5x5InToOut( std::string prefix = std::string() ); 
void Copyph_E5x5InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_E5x5( std::string prefix ); 
void Copyph_E2x5MaxInToOut( std::string prefix = std::string() ); 
void Copyph_E2x5MaxInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_E2x5Max( std::string prefix ); 
void Copyph_SCetaWidthInToOut( std::string prefix = std::string() ); 
void Copyph_SCetaWidthInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_SCetaWidth( std::string prefix ); 
void Copyph_SCphiWidthInToOut( std::string prefix = std::string() ); 
void Copyph_SCphiWidthInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_SCphiWidth( std::string prefix ); 
void Copyph_ESEffSigmaRRInToOut( std::string prefix = std::string() ); 
void Copyph_ESEffSigmaRRInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_ESEffSigmaRR( std::string prefix ); 
void Copyph_hcalIsoDR03InToOut( std::string prefix = std::string() ); 
void Copyph_hcalIsoDR03InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_hcalIsoDR03( std::string prefix ); 
void Copyph_trkIsoHollowDR03InToOut( std::string prefix = std::string() ); 
void Copyph_trkIsoHollowDR03InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_trkIsoHollowDR03( std::string prefix ); 
void Copyph_chgpfIsoDR02InToOut( std::string prefix = std::string() ); 
void Copyph_chgpfIsoDR02InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_chgpfIsoDR02( std::string prefix ); 
void Copyph_pfChIsoWorstInToOut( std::string prefix = std::string() ); 
void Copyph_pfChIsoWorstInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_pfChIsoWorst( std::string prefix ); 
void Copyph_chIsoInToOut( std::string prefix = std::string() ); 
void Copyph_chIsoInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_chIso( std::string prefix ); 
void Copyph_neuIsoInToOut( std::string prefix = std::string() ); 
void Copyph_neuIsoInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_neuIso( std::string prefix ); 
void Copyph_phoIsoInToOut( std::string prefix = std::string() ); 
void Copyph_phoIsoInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_phoIso( std::string prefix ); 
void Copyph_chIsoCorrInToOut( std::string prefix = std::string() ); 
void Copyph_chIsoCorrInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_chIsoCorr( std::string prefix ); 
void Copyph_neuIsoCorrInToOut( std::string prefix = std::string() ); 
void Copyph_neuIsoCorrInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_neuIsoCorr( std::string prefix ); 
void Copyph_phoIsoCorrInToOut( std::string prefix = std::string() ); 
void Copyph_phoIsoCorrInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_phoIsoCorr( std::string prefix ); 
void Copyph_SCRChIsoInToOut( std::string prefix = std::string() ); 
void Copyph_SCRChIsoInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_SCRChIso( std::string prefix ); 
void Copyph_SCRPhoIsoInToOut( std::string prefix = std::string() ); 
void Copyph_SCRPhoIsoInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_SCRPhoIso( std::string prefix ); 
void Copyph_SCRNeuIsoInToOut( std::string prefix = std::string() ); 
void Copyph_SCRNeuIsoInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_SCRNeuIso( std::string prefix ); 
void Copyph_SCRChIso04InToOut( std::string prefix = std::string() ); 
void Copyph_SCRChIso04InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_SCRChIso04( std::string prefix ); 
void Copyph_SCRPhoIso04InToOut( std::string prefix = std::string() ); 
void Copyph_SCRPhoIso04InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_SCRPhoIso04( std::string prefix ); 
void Copyph_SCRNeuIso04InToOut( std::string prefix = std::string() ); 
void Copyph_SCRNeuIso04InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_SCRNeuIso04( std::string prefix ); 
void Copyph_RandConeChIsoInToOut( std::string prefix = std::string() ); 
void Copyph_RandConeChIsoInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_RandConeChIso( std::string prefix ); 
void Copyph_RandConePhoIsoInToOut( std::string prefix = std::string() ); 
void Copyph_RandConePhoIsoInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_RandConePhoIso( std::string prefix ); 
void Copyph_RandConeNeuIsoInToOut( std::string prefix = std::string() ); 
void Copyph_RandConeNeuIsoInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_RandConeNeuIso( std::string prefix ); 
void Copyph_RandConeChIso04InToOut( std::string prefix = std::string() ); 
void Copyph_RandConeChIso04InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_RandConeChIso04( std::string prefix ); 
void Copyph_RandConePhoIso04InToOut( std::string prefix = std::string() ); 
void Copyph_RandConePhoIso04InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_RandConePhoIso04( std::string prefix ); 
void Copyph_RandConeNeuIso04InToOut( std::string prefix = std::string() ); 
void Copyph_RandConeNeuIso04InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_RandConeNeuIso04( std::string prefix ); 
void Copyph_eleVetoInToOut( std::string prefix = std::string() ); 
void Copyph_eleVetoInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_eleVeto( std::string prefix ); 
void Copyph_hasPixSeedInToOut( std::string prefix = std::string() ); 
void Copyph_hasPixSeedInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_hasPixSeed( std::string prefix ); 
void Copyph_drToTrkInToOut( std::string prefix = std::string() ); 
void Copyph_drToTrkInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_drToTrk( std::string prefix ); 
void Copyph_isConvInToOut( std::string prefix = std::string() ); 
void Copyph_isConvInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_isConv( std::string prefix ); 
void Copyph_conv_nTrkInToOut( std::string prefix = std::string() ); 
void Copyph_conv_nTrkInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_conv_nTrk( std::string prefix ); 
void Copyph_conv_vtx_xInToOut( std::string prefix = std::string() ); 
void Copyph_conv_vtx_xInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_conv_vtx_x( std::string prefix ); 
void Copyph_conv_vtx_yInToOut( std::string prefix = std::string() ); 
void Copyph_conv_vtx_yInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_conv_vtx_y( std::string prefix ); 
void Copyph_conv_vtx_zInToOut( std::string prefix = std::string() ); 
void Copyph_conv_vtx_zInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_conv_vtx_z( std::string prefix ); 
void Copyph_conv_ptin1InToOut( std::string prefix = std::string() ); 
void Copyph_conv_ptin1InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_conv_ptin1( std::string prefix ); 
void Copyph_conv_ptin2InToOut( std::string prefix = std::string() ); 
void Copyph_conv_ptin2InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_conv_ptin2( std::string prefix ); 
void Copyph_conv_ptout1InToOut( std::string prefix = std::string() ); 
void Copyph_conv_ptout1InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_conv_ptout1( std::string prefix ); 
void Copyph_conv_ptout2InToOut( std::string prefix = std::string() ); 
void Copyph_conv_ptout2InToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_conv_ptout2( std::string prefix ); 
void Copyph_passTightInToOut( std::string prefix = std::string() ); 
void Copyph_passTightInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_passTight( std::string prefix ); 
void Copyph_passMediumInToOut( std::string prefix = std::string() ); 
void Copyph_passMediumInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_passMedium( std::string prefix ); 
void Copyph_passLooseInToOut( std::string prefix = std::string() ); 
void Copyph_passLooseInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_passLoose( std::string prefix ); 
void Copyph_passLooseNoSIEIEInToOut( std::string prefix = std::string() ); 
void Copyph_passLooseNoSIEIEInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_passLooseNoSIEIE( std::string prefix ); 
void Copyph_passHOverELooseInToOut( std::string prefix = std::string() ); 
void Copyph_passHOverELooseInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_passHOverELoose( std::string prefix ); 
void Copyph_passHOverEMediumInToOut( std::string prefix = std::string() ); 
void Copyph_passHOverEMediumInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_passHOverEMedium( std::string prefix ); 
void Copyph_passHOverETightInToOut( std::string prefix = std::string() ); 
void Copyph_passHOverETightInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_passHOverETight( std::string prefix ); 
void Copyph_passSIEIELooseInToOut( std::string prefix = std::string() ); 
void Copyph_passSIEIELooseInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_passSIEIELoose( std::string prefix ); 
void Copyph_passSIEIEMediumInToOut( std::string prefix = std::string() ); 
void Copyph_passSIEIEMediumInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_passSIEIEMedium( std::string prefix ); 
void Copyph_passSIEIETightInToOut( std::string prefix = std::string() ); 
void Copyph_passSIEIETightInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_passSIEIETight( std::string prefix ); 
void Copyph_passChIsoCorrLooseInToOut( std::string prefix = std::string() ); 
void Copyph_passChIsoCorrLooseInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_passChIsoCorrLoose( std::string prefix ); 
void Copyph_passChIsoCorrMediumInToOut( std::string prefix = std::string() ); 
void Copyph_passChIsoCorrMediumInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_passChIsoCorrMedium( std::string prefix ); 
void Copyph_passChIsoCorrTightInToOut( std::string prefix = std::string() ); 
void Copyph_passChIsoCorrTightInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_passChIsoCorrTight( std::string prefix ); 
void Copyph_passNeuIsoCorrLooseInToOut( std::string prefix = std::string() ); 
void Copyph_passNeuIsoCorrLooseInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_passNeuIsoCorrLoose( std::string prefix ); 
void Copyph_passNeuIsoCorrMediumInToOut( std::string prefix = std::string() ); 
void Copyph_passNeuIsoCorrMediumInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_passNeuIsoCorrMedium( std::string prefix ); 
void Copyph_passNeuIsoCorrTightInToOut( std::string prefix = std::string() ); 
void Copyph_passNeuIsoCorrTightInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_passNeuIsoCorrTight( std::string prefix ); 
void Copyph_passPhoIsoCorrLooseInToOut( std::string prefix = std::string() ); 
void Copyph_passPhoIsoCorrLooseInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_passPhoIsoCorrLoose( std::string prefix ); 
void Copyph_passPhoIsoCorrMediumInToOut( std::string prefix = std::string() ); 
void Copyph_passPhoIsoCorrMediumInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_passPhoIsoCorrMedium( std::string prefix ); 
void Copyph_passPhoIsoCorrTightInToOut( std::string prefix = std::string() ); 
void Copyph_passPhoIsoCorrTightInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_passPhoIsoCorrTight( std::string prefix ); 
void Copyph_truthMatch_elInToOut( std::string prefix = std::string() ); 
void Copyph_truthMatch_elInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_truthMatch_el( std::string prefix ); 
void Copyph_truthMinDR_elInToOut( std::string prefix = std::string() ); 
void Copyph_truthMinDR_elInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_truthMinDR_el( std::string prefix ); 
void Copyph_truthMatchPt_elInToOut( std::string prefix = std::string() ); 
void Copyph_truthMatchPt_elInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_truthMatchPt_el( std::string prefix ); 
void Copyph_truthMatch_phInToOut( std::string prefix = std::string() ); 
void Copyph_truthMatch_phInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_truthMatch_ph( std::string prefix ); 
void Copyph_truthMinDR_phInToOut( std::string prefix = std::string() ); 
void Copyph_truthMinDR_phInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_truthMinDR_ph( std::string prefix ); 
void Copyph_truthMatchPt_phInToOut( std::string prefix = std::string() ); 
void Copyph_truthMatchPt_phInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_truthMatchPt_ph( std::string prefix ); 
void Copyph_truthMatchMotherPID_phInToOut( std::string prefix = std::string() ); 
void Copyph_truthMatchMotherPID_phInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_truthMatchMotherPID_ph( std::string prefix ); 
void Copyph_hasSLConvInToOut( std::string prefix = std::string() ); 
void Copyph_hasSLConvInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_hasSLConv( std::string prefix ); 
void Copyph_pass_mva_preselInToOut( std::string prefix = std::string() ); 
void Copyph_pass_mva_preselInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_pass_mva_presel( std::string prefix ); 
void Copyph_mvascoreInToOut( std::string prefix = std::string() ); 
void Copyph_mvascoreInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_mvascore( std::string prefix ); 
void Copyph_IsEBInToOut( std::string prefix = std::string() ); 
void Copyph_IsEBInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_IsEB( std::string prefix ); 
void Copyph_IsEEInToOut( std::string prefix = std::string() ); 
void Copyph_IsEEInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_IsEE( std::string prefix ); 
void Copyjet_ptInToOut( std::string prefix = std::string() ); 
void Copyjet_ptInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputjet_pt( std::string prefix ); 
void Copyjet_etaInToOut( std::string prefix = std::string() ); 
void Copyjet_etaInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputjet_eta( std::string prefix ); 
void Copyjet_phiInToOut( std::string prefix = std::string() ); 
void Copyjet_phiInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputjet_phi( std::string prefix ); 
void Copyjet_eInToOut( std::string prefix = std::string() ); 
void Copyjet_eInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputjet_e( std::string prefix ); 
void CopyPUWeightInToOut( std::string prefix = std::string() ); 
void CopyisBlindedInToOut( std::string prefix = std::string() ); 
void CopyEventWeightInToOut( std::string prefix = std::string() ); 
void Copymu_pt25_nInToOut( std::string prefix = std::string() ); 
void Copymu_passtrig_nInToOut( std::string prefix = std::string() ); 
void Copymu_passtrig25_nInToOut( std::string prefix = std::string() ); 
void Copyel_pt25_nInToOut( std::string prefix = std::string() ); 
void Copyel_passtrig_nInToOut( std::string prefix = std::string() ); 
void Copyel_passtrig28_nInToOut( std::string prefix = std::string() ); 
void Copyph_mediumNoSIEIE_nInToOut( std::string prefix = std::string() ); 
void Copyph_medium_nInToOut( std::string prefix = std::string() ); 
void Copyph_mediumNoEleVeto_nInToOut( std::string prefix = std::string() ); 
void Copyph_mediumNoSIEIENoEleVeto_nInToOut( std::string prefix = std::string() ); 
void Copyph_mediumNoIso_nInToOut( std::string prefix = std::string() ); 
void Copyph_mediumNoChIso_nInToOut( std::string prefix = std::string() ); 
void Copyph_mediumNoNeuIso_nInToOut( std::string prefix = std::string() ); 
void Copyph_mediumNoPhoIso_nInToOut( std::string prefix = std::string() ); 
void Copyph_mediumNoChIsoNoNeuIso_nInToOut( std::string prefix = std::string() ); 
void Copyph_mediumNoChIsoNoPhoIso_nInToOut( std::string prefix = std::string() ); 
void Copyph_mediumNoNeuIsoNoPhoIso_nInToOut( std::string prefix = std::string() ); 
void Copyph_trigMatch_elInToOut( std::string prefix = std::string() ); 
void Copyph_trigMatch_elInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputph_trigMatch_el( std::string prefix ); 
void CopyleadPhot_ptInToOut( std::string prefix = std::string() ); 
void CopysublPhot_ptInToOut( std::string prefix = std::string() ); 
void CopyleadPhot_lepDRInToOut( std::string prefix = std::string() ); 
void CopysublPhot_lepDRInToOut( std::string prefix = std::string() ); 
void Copyph_phDRInToOut( std::string prefix = std::string() ); 
void CopyphPhot_lepDRInToOut( std::string prefix = std::string() ); 
void CopyleadPhot_lepDPhiInToOut( std::string prefix = std::string() ); 
void CopysublPhot_lepDPhiInToOut( std::string prefix = std::string() ); 
void Copyph_phDPhiInToOut( std::string prefix = std::string() ); 
void CopyphPhot_lepDPhiInToOut( std::string prefix = std::string() ); 
void Copydphi_met_lep1InToOut( std::string prefix = std::string() ); 
void Copydphi_met_lep2InToOut( std::string prefix = std::string() ); 
void Copydphi_met_ph1InToOut( std::string prefix = std::string() ); 
void Copydphi_met_ph2InToOut( std::string prefix = std::string() ); 
void Copymt_lep_metInToOut( std::string prefix = std::string() ); 
void Copymt_lepph1_metInToOut( std::string prefix = std::string() ); 
void Copymt_lepph2_metInToOut( std::string prefix = std::string() ); 
void Copymt_lepphph_metInToOut( std::string prefix = std::string() ); 
void Copym_leplepInToOut( std::string prefix = std::string() ); 
void Copym_lepph1InToOut( std::string prefix = std::string() ); 
void Copym_lepph2InToOut( std::string prefix = std::string() ); 
void Copym_leplepphInToOut( std::string prefix = std::string() ); 
void Copym_lepphphInToOut( std::string prefix = std::string() ); 
void Copym_phphInToOut( std::string prefix = std::string() ); 
void Copym_leplepZInToOut( std::string prefix = std::string() ); 
void Copym_3lepInToOut( std::string prefix = std::string() ); 
void Copym_4lepInToOut( std::string prefix = std::string() ); 
void Copypt_phphInToOut( std::string prefix = std::string() ); 
void Copypt_leplepInToOut( std::string prefix = std::string() ); 
void Copypt_lepph1InToOut( std::string prefix = std::string() ); 
void Copypt_lepph2InToOut( std::string prefix = std::string() ); 
void Copypt_lepphphInToOut( std::string prefix = std::string() ); 
void Copypt_leplepphInToOut( std::string prefix = std::string() ); 
void Copypt_secondLeptonInToOut( std::string prefix = std::string() ); 
void Copypt_thirdLeptonInToOut( std::string prefix = std::string() ); 
void CopyleadPhot_leadLepDRInToOut( std::string prefix = std::string() ); 
void CopyleadPhot_sublLepDRInToOut( std::string prefix = std::string() ); 
void CopysublPhot_leadLepDRInToOut( std::string prefix = std::string() ); 
void CopysublPhot_sublLepDRInToOut( std::string prefix = std::string() ); 
void Copym_nearestToZInToOut( std::string prefix = std::string() ); 
void Copym_minZdifflepphInToOut( std::string prefix = std::string() ); 
void Copytruelep_nInToOut( std::string prefix = std::string() ); 
void Copytrueph_nInToOut( std::string prefix = std::string() ); 
void Copytrueph_wmother_nInToOut( std::string prefix = std::string() ); 
void Copytruegenph_nInToOut( std::string prefix = std::string() ); 
void Copytruegenphpt15_nInToOut( std::string prefix = std::string() ); 
void Copytruelep_ptInToOut( std::string prefix = std::string() ); 
void Copytruelep_ptInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtruelep_pt( std::string prefix ); 
void Copytruelep_etaInToOut( std::string prefix = std::string() ); 
void Copytruelep_etaInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtruelep_eta( std::string prefix ); 
void Copytruelep_phiInToOut( std::string prefix = std::string() ); 
void Copytruelep_phiInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtruelep_phi( std::string prefix ); 
void Copytruelep_eInToOut( std::string prefix = std::string() ); 
void Copytruelep_eInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtruelep_e( std::string prefix ); 
void Copytruelep_isElecInToOut( std::string prefix = std::string() ); 
void Copytruelep_isElecInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtruelep_isElec( std::string prefix ); 
void Copytruelep_isMuonInToOut( std::string prefix = std::string() ); 
void Copytruelep_isMuonInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtruelep_isMuon( std::string prefix ); 
void Copytruelep_motherPIDInToOut( std::string prefix = std::string() ); 
void Copytruelep_motherPIDInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtruelep_motherPID( std::string prefix ); 
void Copytrueph_ptInToOut( std::string prefix = std::string() ); 
void Copytrueph_ptInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtrueph_pt( std::string prefix ); 
void Copytrueph_etaInToOut( std::string prefix = std::string() ); 
void Copytrueph_etaInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtrueph_eta( std::string prefix ); 
void Copytrueph_phiInToOut( std::string prefix = std::string() ); 
void Copytrueph_phiInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtrueph_phi( std::string prefix ); 
void Copytrueph_motherPIDInToOut( std::string prefix = std::string() ); 
void Copytrueph_motherPIDInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtrueph_motherPID( std::string prefix ); 
void Copytrueph_parentageInToOut( std::string prefix = std::string() ); 
void Copytrueph_parentageInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtrueph_parentage( std::string prefix ); 
void Copytrueph_nearestLepDRInToOut( std::string prefix = std::string() ); 
void Copytrueph_nearestLepDRInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtrueph_nearestLepDR( std::string prefix ); 
void Copytrueph_nearestQrkDRInToOut( std::string prefix = std::string() ); 
void Copytrueph_nearestQrkDRInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputtrueph_nearestQrkDR( std::string prefix ); 
void Copytrueleadlep_ptInToOut( std::string prefix = std::string() ); 
void Copytruesubllep_ptInToOut( std::string prefix = std::string() ); 
void Copytrueleadlep_leadPhotDRInToOut( std::string prefix = std::string() ); 
void Copytrueleadlep_sublPhotDRInToOut( std::string prefix = std::string() ); 
void Copytruesubllep_leadPhotDRInToOut( std::string prefix = std::string() ); 
void Copytruesubllep_sublPhotDRInToOut( std::string prefix = std::string() ); 
#endif
