// Class: ReadkNN
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : KNN::kNN
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/07       [336391]
Creator        : jkunkle
Date           : Tue Apr 29 13:56:17 2014
Host           : Linux lxbuild175.cern.ch 2.6.18-308.4.1.el5 #1 SMP Wed Apr 18 16:26:27 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/user/j/jkunkle/usercode/Analysis/TreeFilter/TrainPhotonMVA
Training events: 9667
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
# Default:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
nkNN: "20" [Number of k-nearest neighbors]
BalanceDepth: "6" [Binary tree balance depth]
ScaleFrac: "8.000000e-01" [Fraction of events used to compute variable width]
SigmaFact: "1.000000e+00" [Scale factor for sigma in Gaussian kernel]
Kernel: "Gaus" [Use polynomial (=Poln) or Gaussian (=Gaus) kernel]
Trim: "False" [Use equal number of signal and background events]
UseKernel: "False" [Use polynomial kernel weight]
UseWeight: "True" [Use weight to count kNN events]
UseLDA: "False" [Use local linear discriminant - experimental feature]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 7
m_lepphphMod                  m_lepphphMod                  m_lepphphMod                  m_lepphphMod                                                    'F'    [-91.1999969482,1559.67114258]
m_lepph1Mod                   m_lepph1Mod                   m_lepph1Mod                   m_lepph1Mod                                                     'F'    [-91.1999969482,1098.84509277]
m_lepph2Mod                   m_lepph2Mod                   m_lepph2Mod                   m_lepph2Mod                                                     'F'    [-91.1999969482,745.56036377]
m_phph                        m_phph                        m_phph                        m_phph                                                          'F'    [2.01464343071,1540.8671875]
leadPhot_leadLepDR            leadPhot_leadLepDR            leadPhot_leadLepDR            leadPhot_leadLepDR                                              'F'    [0.204598933458,5.33279561996]
sublPhot_leadLepDR            sublPhot_leadLepDR            sublPhot_leadLepDR            sublPhot_leadLepDR                                              'F'    [0.207107365131,5.50843191147]
ph_phDR                       ph_phDR                       ph_phDR                       ph_phDR                                                         'F'    [0,5.68566608429]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadkNN : public IClassifierReader {

 public:

   // constructor
   ReadkNN( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadkNN" ),
        fNvars( 7 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "m_lepphphMod", "m_lepph1Mod", "m_lepph2Mod", "m_phph", "leadPhot_leadLepDR", "sublPhot_leadLepDR", "ph_phDR" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = -91.1999969482422;
      fVmax[0] = 1559.67114257812;
      fVmin[1] = -91.1999969482422;
      fVmax[1] = 1098.84509277344;
      fVmin[2] = -91.1999969482422;
      fVmax[2] = 745.560363769531;
      fVmin[3] = 2.01464343070984;
      fVmax[3] = 1540.8671875;
      fVmin[4] = 0.204598933458328;
      fVmax[4] = 5.3327956199646;
      fVmin[5] = 0.207107365131378;
      fVmax[5] = 5.50843191146851;
      fVmin[6] = 0;
      fVmax[6] = 5.68566608428955;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadkNN() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[7];
   double fVmax[7];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[7];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   // not implemented for class: "ReadkNN"
};
   inline double ReadkNN::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
