// Class: ReadBDT
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT
TMVA Release   : 4.1.4         [262404]
ROOT Release   : 5.34/07       [336391]
Creator        : jkunkle
Date           : Wed Apr 16 02:38:40 2014
Host           : Linux lxbuild175.cern.ch 2.6.18-308.4.1.el5 #1 SMP Wed Apr 18 16:26:27 CEST 2012 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /afs/cern.ch/user/j/jkunkle/usercode/Analysis/TreeFilter/TrainPhotonMVA
Training events: 4478159
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
# Default:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
H: "False" [Print method-specific help message]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
NTrees: "400" [Number of trees in the forest]
RenormByClass: "False" [Individually re-normalize each event class to the original size after boosting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2t (Linear,Quadratic or Exponential)]
UseBaggedGrad: "False" [Use only a random subsample of all events for growing the trees in each iteration. (Only valid for GradBoost)]
GradBaggingFraction: "6.000000e-01" [Defines the fraction of events to be used in each iteration when UseBaggedGrad=kTRUE. (Only valid for GradBoost)]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "1.000000e+00" [Parameter for AdaBoost algorithm]
UseRandomisedTrees: "False" [Choose at each node splitting a random set of variables]
UseNvars: "2" [Number of variables used if randomised tree option is chosen]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split]
UseNTrainEvents: "4478159" [Number of randomly picked training events used in randomised (and bagged) trees]
UseWeightedTrees: "True" [Use weighted trees or simple average in classification from the forest]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
SeparationType: "giniindex" [Separation criterion for node splitting]
nEventsMin: "49757" [Minimum number of events required in a leaf node (default: Classification: max(40, N_train/(Nvar^2)/10), Regression: 10)]
nCuts: "20" [Number of steps during node cut optimisation]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
PruneStrength: "0.000000e+00" [Pruning strength]
PruneMethod: "nopruning" [Method used for pruning (removal) of statistically insignificant branches]
PruneBeforeBoost: "False" [Flag to prune the tree before applying boosting algorithm]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
NNodesMax: "100000" [Max number of nodes in tree]
MaxDepth: "3" [Max depth of the decision tree allowed]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : Ignore;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!); Randomly pair events with negative and positive weights in leaf node and do not boost them (experimental!) ]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 3
phoPFChIsoPtRhoCorr           phoPFChIsoPtRhoCorr           phoPFChIsoPtRhoCorr           phoPFChIsoPtRhoCorr                                             'F'    [0,75.3367996216]
phoPFNeuIsoPtRhoCorr          phoPFNeuIsoPtRhoCorr          phoPFNeuIsoPtRhoCorr          phoPFNeuIsoPtRhoCorr                                            'F'    [-7.99977302551,130.464950562]
phoPFPhoIsoPtRhoCorr          phoPFPhoIsoPtRhoCorr          phoPFPhoIsoPtRhoCorr          phoPFPhoIsoPtRhoCorr                                            'F'    [-0.999971628189,204.118347168]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDTNode
   
#ifndef BDTNode__def
#define BDTNode__def
   
class BDTNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDTNode ( BDTNode* left,BDTNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDTNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDTNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDTNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDTNode*   fLeft;     // pointer to the left daughter node
   BDTNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDTNode::~BDTNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDTNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDTNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT : public IClassifierReader {

 public:

   // constructor
   ReadBDT( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT" ),
        fNvars( 3 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "phoPFChIsoPtRhoCorr", "phoPFNeuIsoPtRhoCorr", "phoPFPhoIsoPtRhoCorr" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 75.336799621582;
      fVmin[1] = -7.9997730255127;
      fVmax[1] = 130.464950561523;
      fVmin[2] = -0.999971628189087;
      fVmax[2] = 204.118347167969;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[3];
   double fVmax[3];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[3];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDTNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDTNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDTNode*)current->GetRight();
         else current=(BDTNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(2.0956144772472);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -1.72019, 1, 1, 0.974432,-99) , 
NN(
NN(
0, 
0, 
-1, 1.19559, 1, 1, 0.766473,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366661,-99) , 
0, 3.13844, 1, 0, 0.747485,-99) , 
1, -1.40621, 1, 0, 0.885514,-99)    );
  // itree = 1
  fBoostWeights.push_back(1.16247);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, -2.03417, 1, 1, 0.824178,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.824776,-99) , 
NN(
0, 
0, 
-1, 0.747243, 1, -1, 0.287591,-99) , 
0, 3.13844, 0, 0, 0.321613,-99) , 
1, -1.40621, 1, 0, 0.524529,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.630367);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -1.40621, 1, 1, 0.651052,-99) , 
NN(
0, 
0, 
-1, 1.50494, 1, -1, 0.331957,-99) , 
0, 0.854156, 1, 0, 0.582096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406823,-99) , 
0, 3.58747, 1, 0, 0.57597,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.145865);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562977,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545883,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483121,-99) , 
1, -1.40621, 1, 0, 0.505869,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508901,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.355323,-99) , 
0, 3.01802, 0, 0, 0.398907,-99) , 
0, 1.87914, 1, 0, 0.494992,-99) , 
0, 3.58747, 0, 0, 0.497463,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.349509);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.704971,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519905,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.266885,-99) , 
2, 3.01152, 1, 0, 0.509094,-99) , 
0, 3.13844, 0, 0, 0.52092,-99) , 
NN(
NN(
0, 
0, 
-1, -2.60233, 1, 1, 0.661146,-99) , 
NN(
0, 
0, 
-1, -1.70524, 1, -1, 0.319515,-99) , 
1, -2.03417, 1, 0, 0.480054,-99) , 
1, -1.40621, 0, 0, 0.506386,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.343159);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -3.15553, 1, 1, 0.6389,-99) , 
NN(
0, 
0, 
-1, -1.63049, 1, -1, 0.41002,-99) , 
1, -2.34815, 1, 0, 0.484328,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.627515,-99) , 
NN(
0, 
0, 
-1, 2.09228, 1, -1, 0.429277,-99) , 
0, 3.13844, 0, 0, 0.440551,-99) , 
1, -1.40621, 1, 0, 0.455649,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.152664);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.87856, 0, 1, 0.530499,-99) , 
NN(
0, 
0, 
-1, -1.50218, 0, -1, 0.396712,-99) , 
0, 2.04997, 1, 0, 0.518903,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425806,-99) , 
0, 3.58747, 1, 0, 0.515704,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.0964618);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486261,-99) , 
0, 0.894828, 0, 0, 0.493902,-99) , 
NN(
0, 
0, 
-1, -1.50218, 0, -1, 0.435785,-99) , 
0, 1.70831, 1, 0, 0.487343,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463486,-99) , 
0, 3.58747, 1, 0, 0.486528,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.0890454);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -1.40621, 1, 1, 0.521461,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.643921,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477257,-99) , 
1, -3.8319, 1, 0, 0.479951,-99) , 
0, 0.170831, 1, 0, 0.506974,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487539,-99) , 
0, 3.58747, 1, 0, 0.50631,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.117867);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.626349,-99) , 
NN(
0, 
0, 
-1, 3.01152, 1, -1, 0.494446,-99) , 
0, 3.13844, 0, 0, 0.502038,-99) , 
NN(
NN(
0, 
0, 
-1, -3.21534, 1, 1, 0.54338,-99) , 
NN(
0, 
0, 
-1, -1.54078, 1, -1, 0.397011,-99) , 
1, -1.72019, 1, 0, 0.497044,-99) , 
1, -1.40621, 0, 0, 0.500339,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.138312);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.598379,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527309,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438773,-99) , 
2, 3.01152, 1, 0, 0.523894,-99) , 
0, 3.13844, 0, 0, 0.528124,-99) , 
NN(
NN(
0, 
0, 
-1, -4.63571, 1, 1, 0.618007,-99) , 
NN(
0, 
0, 
-1, -1.58563, 1, -1, 0.4709,-99) , 
1, -3.29009, 1, 0, 0.486145,-99) , 
1, -1.40621, 0, 0, 0.513895,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.107451);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -4.11242, 1, 1, 0.53821,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506365,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409454,-99) , 
1, -1.54078, 1, 0, 0.459649,-99) , 
1, -1.72019, 1, 0, 0.513584,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564736,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522553,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484472,-99) , 
0, 0.896692, 0, 0, 0.492003,-99) , 
0, 3.13844, 0, 0, 0.496096,-99) , 
1, -1.40621, 1, 0, 0.50202,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0789736);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.878558, 0, 1, 0.51457,-99) , 
NN(
0, 
0, 
-1, 2.51366, 1, -1, 0.454354,-99) , 
0, 1.53748, 1, 0, 0.506849,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446472,-99) , 
0, 3.58747, 1, 0, 0.504815,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0622173);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557723,-99) , 
NN(
0, 
0, 
-1, 2.39118, 1, -1, 0.493113,-99) , 
0, 3.13844, 0, 0, 0.496746,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594198,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491144,-99) , 
1, -4.11242, 1, 0, 0.497138,-99) , 
NN(
0, 
0, 
-1, -1.60058, 1, -1, 0.444506,-99) , 
1, -1.72019, 1, 0, 0.480597,-99) , 
1, -1.40621, 0, 0, 0.491288,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0518244);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.854153, 0, 1, 0.509937,-99) , 
NN(
0, 
0, 
-1, 2.95296, 1, -1, 0.450069,-99) , 
0, 2.56247, 1, 0, 0.506846,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459528,-99) , 
0, 3.58747, 1, 0, 0.505265,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0596746);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555158,-99) , 
NN(
0, 
0, 
-1, 2.39118, 1, -1, 0.496603,-99) , 
0, 3.13844, 0, 0, 0.499895,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537707,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483392,-99) , 
1, -2.01923, 0, 0, 0.4998,-99) , 
NN(
0, 
0, 
-1, -1.60058, 1, -1, 0.448959,-99) , 
1, -1.72019, 1, 0, 0.483818,-99) , 
1, -1.40621, 0, 0, 0.494467,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0667839);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540377,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512748,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485978,-99) , 
0, 2.39118, 1, 0, 0.51152,-99) , 
0, 3.13844, 0, 0, 0.513137,-99) , 
NN(
NN(
0, 
0, 
-1, -4.65067, 1, 1, 0.546794,-99) , 
NN(
0, 
0, 
-1, -1.63049, 1, -1, 0.483138,-99) , 
1, -2.97611, 1, 0, 0.49254,-99) , 
1, -1.40621, 0, 0, 0.50619,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0342248);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524325,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498095,-99) , 
0, 0.829749, 0, 0, 0.503056,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456238,-99) , 
0, 2.90413, 1, 0, 0.501546,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456472,-99) , 
0, 3.58747, 1, 0, 0.500054,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0473282);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.84602, 0, 1, 0.510529,-99) , 
NN(
0, 
0, 
-1, -1.50218, 0, -1, 0.485964,-99) , 
0, 1.36665, 1, 0, 0.506972,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464976,-99) , 
0, 3.58747, 1, 0, 0.505583,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0327037);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.11447, 1, 1, 0.514754,-99) , 
NN(
0, 
0, 
-1, 0.569437, 1, -1, 0.494237,-99) , 
0, 0.854156, 0, 0, 0.498567,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476767,-99) , 
0, 3.58747, 1, 0, 0.497847,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0372259);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -1.40621, 1, 1, 0.508181,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50253,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468019,-99) , 
0, 0.805348, 0, 0, 0.492401,-99) , 
0, 0.341662, 1, 0, 0.503292,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484931,-99) , 
0, 3.58747, 1, 0, 0.502686,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0620018);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526467,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493998,-99) , 
1, -2.31825, 0, 0, 0.510845,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516777,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455357,-99) , 
1, -1.60058, 1, 0, 0.47588,-99) , 
1, -1.72019, 1, 0, 0.499871,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548207,-99) , 
NN(
0, 
0, 
-1, 3.01152, 1, -1, 0.490218,-99) , 
0, 3.13844, 0, 0, 0.493476,-99) , 
1, -1.40621, 1, 0, 0.49563,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0392679);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509203,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496394,-99) , 
0, 1.24462, 1, 0, 0.507532,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456519,-99) , 
0, 2.90413, 1, 0, 0.505889,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483873,-99) , 
0, 3.58747, 1, 0, 0.505165,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0454356);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54257,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51252,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495472,-99) , 
0, 0.896692, 0, 0, 0.498828,-99) , 
0, 3.13844, 0, 0, 0.501284,-99) , 
NN(
NN(
0, 
0, 
-1, -4.69552, 1, 1, 0.528307,-99) , 
NN(
0, 
0, 
-1, -2.3631, 0, -1, 0.485234,-99) , 
1, -2.66213, 1, 0, 0.494507,-99) , 
1, -1.40621, 0, 0, 0.499003,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0336896);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509475,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499913,-99) , 
0, 0.553166, 1, 0, 0.507186,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459969,-99) , 
0, 2.90413, 1, 0, 0.505669,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487472,-99) , 
0, 3.58747, 1, 0, 0.505071,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0197322);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 3.13844, 0, 1, 0.503788,-99) , 
NN(
NN(
0, 
0, 
-1, -5.5328, 1, 1, 0.586542,-99) , 
NN(
0, 
0, 
-1, -1.55573, 1, -1, 0.494772,-99) , 
1, -4.546, 1, 0, 0.496989,-99) , 
1, -1.40621, 0, 0, 0.501501,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0308675);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -5.5328, 1, 1, 0.581749,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504794,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474728,-99) , 
1, -1.55573, 1, 0, 0.499705,-99) , 
1, -4.546, 1, 0, 0.501684,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534748,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511747,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495632,-99) , 
0, 2.09228, 0, 0, 0.496722,-99) , 
0, 3.13844, 0, 0, 0.498855,-99) , 
1, -1.40621, 1, 0, 0.499806,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0266373);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527061,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504155,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484359,-99) , 
2, 3.01152, 1, 0, 0.503395,-99) , 
0, 3.13844, 0, 0, 0.504721,-99) , 
NN(
NN(
0, 
0, 
-1, -5.5328, 1, 1, 0.57422,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501063,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485895,-99) , 
1, -1.85475, 1, 0, 0.494599,-99) , 
1, -4.546, 1, 0, 0.496515,-99) , 
1, -1.40621, 0, 0, 0.501961,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0301771);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514215,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496028,-99) , 
0, 0.829749, 0, 0, 0.499464,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45449,-99) , 
0, 2.90413, 1, 0, 0.498018,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481754,-99) , 
0, 3.58747, 1, 0, 0.497485,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0273662);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505712,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495436,-99) , 
0, 1.17141, 1, 0, 0.504363,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466656,-99) , 
0, 2.7333, 1, 0, 0.502804,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489292,-99) , 
0, 3.58747, 1, 0, 0.502361,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0230779);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534757,-99) , 
NN(
0, 
0, 
-1, 0.149449, 0, -1, 0.497176,-99) , 
0, 3.13844, 0, 0, 0.499284,-99) , 
NN(
NN(
0, 
0, 
-1, -5.5328, 1, 1, 0.568473,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500571,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480677,-99) , 
1, -2.30329, 0, 0, 0.494217,-99) , 
1, -4.546, 1, 0, 0.496,-99) , 
1, -1.40621, 0, 0, 0.49818,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.025729);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 3.13844, 0, 1, 0.504407,-99) , 
NN(
NN(
0, 
0, 
-1, -5.5328, 1, 1, 0.562803,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503693,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489718,-99) , 
1, -2.75183, 1, 0, 0.492132,-99) , 
1, -4.546, 1, 0, 0.493827,-99) , 
1, -1.40621, 0, 0, 0.50085,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0225859);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510055,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496911,-99) , 
0, 0.829749, 0, 0, 0.499394,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46355,-99) , 
0, 2.90413, 1, 0, 0.498244,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488019,-99) , 
0, 3.58747, 1, 0, 0.497909,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0166773);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, -1.40621, 1, 1, 0.503089,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472518,-99) , 
0, 2.7333, 1, 0, 0.501826,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493664,-99) , 
0, 3.58747, 1, 0, 0.501559,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.00801691);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.497996,-99)    );
  // itree = 35
  fBoostWeights.push_back(3.64793e-11);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 36
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 37
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 38
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 39
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 40
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 41
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 42
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 43
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 44
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 45
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 46
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 47
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 48
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 49
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 50
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 51
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 52
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 53
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 54
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 55
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 56
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 57
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 58
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 59
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 60
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 61
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 62
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 63
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 64
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 65
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 66
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 67
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 68
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 69
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 70
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 71
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 72
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 73
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 74
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 75
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 76
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 77
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 78
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 79
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 80
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 81
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 82
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 83
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 84
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 85
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 86
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 87
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 88
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 89
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 90
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 91
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 92
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 93
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 94
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 95
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 96
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 97
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 98
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 99
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 100
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 101
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 102
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 103
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 104
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 105
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 106
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 107
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 108
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 109
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 110
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 111
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 112
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 113
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 114
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 115
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 116
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 117
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 118
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 119
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 120
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 121
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 122
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 123
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 124
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 125
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 126
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 127
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 128
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 129
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 130
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 131
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 132
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 133
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 134
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 135
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 136
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 137
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 138
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 139
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 140
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 141
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 142
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 143
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 144
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 145
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 146
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 147
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 148
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 149
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 150
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 151
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 152
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 153
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 154
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 155
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 156
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 157
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 158
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 159
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 160
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 161
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 162
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 163
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 164
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 165
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 166
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 167
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 168
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 169
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 170
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 171
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 172
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 173
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 174
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 175
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 176
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 177
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 178
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 179
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 180
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 181
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 182
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 183
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 184
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 185
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 186
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 187
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 188
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 189
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 190
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 191
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 192
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 193
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 194
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 195
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 196
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 197
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 198
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 199
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 200
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 201
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 202
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 203
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 204
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 205
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 206
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 207
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 208
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 209
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 210
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 211
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 212
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 213
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 214
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 215
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 216
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 217
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 218
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 219
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 220
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 221
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 222
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 223
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 224
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 225
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 226
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 227
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 228
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 229
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 230
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 231
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 232
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 233
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 234
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 235
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 236
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 237
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 238
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 239
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 240
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 241
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 242
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 243
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 244
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 245
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 246
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 247
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 248
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 249
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 250
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 251
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 252
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 253
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 254
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 255
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 256
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 257
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 258
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 259
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 260
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 261
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 262
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 263
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 264
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 265
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 266
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 267
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 268
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 269
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 270
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 271
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 272
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 273
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 274
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 275
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 276
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 277
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 278
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 279
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 280
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 281
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 282
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 283
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 284
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 285
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 286
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 287
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 288
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 289
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 290
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 291
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 292
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 293
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 294
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 295
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 296
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 297
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 298
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 299
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 300
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 301
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 302
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 303
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 304
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 305
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 306
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 307
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 308
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 309
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 310
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 311
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 312
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 313
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 314
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 315
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 316
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 317
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 318
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 319
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 320
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 321
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 322
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 323
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 324
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 325
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 326
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 327
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 328
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 329
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 330
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 331
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 332
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 333
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 334
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 335
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 336
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 337
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 338
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 339
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 340
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 341
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 342
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 343
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 344
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 345
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 346
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 347
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 348
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 349
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 350
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 351
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 352
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 353
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 354
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 355
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 356
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 357
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 358
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 359
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 360
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 361
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 362
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 363
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 364
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 365
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 366
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 367
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 368
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 369
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 370
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 371
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 372
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 373
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 374
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 375
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 376
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 377
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 378
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 379
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 380
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 381
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 382
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 383
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 384
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 385
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 386
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 387
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 388
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 389
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 390
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 391
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 392
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 393
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 394
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 395
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 396
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 397
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 398
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
  // itree = 399
  fBoostWeights.push_back(0);
  fForest.push_back( 
NN(
0, 
0, 
0, 3.58747, 1, -1, 0.5,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
