#include <algorithm>
#include <iostream>
#include "TTree.h"
#include "TChain.h"
#include "include/BranchInit.h"
#include "include/BranchDefs.h"

namespace IN {
 Int_t				nHLT;
 Int_t				nVtx;
 Int_t				nVtxBS;
 Int_t				nMC;
 Int_t				nPUInfo;
 Int_t				nEle;
 Int_t				nPho;
 Int_t				nMu;
 Int_t				nPFPho;
 Int_t				nJet;
 Int_t				nConv;
 Int_t				nLowPtJet;
 Int_t				run;
 Long64_t				event;
 Int_t				lumis;
 Bool_t				isData;
 Int_t				HLT[444];
 Int_t				HLTIndex[70];
 Float_t				bspotPos[3];
 Float_t				vtx[63][3];
 Int_t				IsVtxGood;
 Int_t				nGoodVtx;
 Float_t				vtxbs[63][3];
 Float_t				pdf[7];
 Float_t				pthat;
 Float_t				processID;
 Int_t				mcPID[97];
 Float_t				mcPt[97];
 Float_t				mcEta[97];
 Float_t				mcPhi[97];
 Float_t				mcE[97];
 Int_t				mcGMomPID[97];
 Int_t				mcMomPID[97];
 Float_t				mcMomPt[97];
 Float_t				mcMomMass[97];
 Float_t				mcMomEta[97];
 Float_t				mcMomPhi[97];
 Int_t				mcIndex[97];
 Int_t				mcDecayType[97];
 Int_t				mcParentage[97];
 Int_t				mcStatus[97];
 Float_t				genMET;
 Float_t				genMETPhi;
 Int_t				nPU[4];
 Int_t				puBX[4];
 Float_t				puTrue[4];
 Float_t				pfMET;
 Float_t				pfMETPhi;
 Float_t				pfMETsumEt;
 Float_t				pfMETmEtSig;
 Float_t				pfMETSig;
 Float_t				recoPfMET;
 Float_t				recoPfMETPhi;
 Float_t				recoPfMETsumEt;
 Float_t				recoPfMETmEtSig;
 Float_t				recoPfMETSig;
 Float_t				trkMETxPV;
 Float_t				trkMETyPV;
 Float_t				trkMETPhiPV;
 Float_t				trkMETPV;
 Float_t				trkMETx[63];
 Float_t				trkMETy[63];
 Float_t				trkMETPhi[63];
 Float_t				trkMET[63];
 Int_t				metFilters[10];
 Int_t				eleTrg[11][16];
 Int_t				eleClass[11];
 Int_t				eleIsEcalDriven[11];
 Int_t				eleCharge[11];
 Float_t				eleEn[11];
 Float_t				eleEcalEn[11];
 Float_t				eleSCRawEn[11];
 Float_t				eleSCEn[11];
 Float_t				eleESEn[11];
 Float_t				elePt[11];
 Float_t				eleEta[11];
 Float_t				elePhi[11];
 Float_t				eleSCEta[11];
 Float_t				eleSCPhi[11];
 Float_t				eleSCEtaWidth[11];
 Float_t				eleSCPhiWidth[11];
 Float_t				eleVtx[11][3];
 Float_t				eleD0[11];
 Float_t				eleDz[11];
 Float_t				eleD0GV[11];
 Float_t				eleDzGV[11];
 Float_t				eleHoverE[11];
 Float_t				eleHoverE12[11];
 Float_t				eleEoverP[11];
 Float_t				elePin[11];
 Float_t				elePout[11];
 Float_t				eleTrkMomErr[11];
 Float_t				eleBrem[11];
 Float_t				eledEtaAtVtx[11];
 Float_t				eledPhiAtVtx[11];
 Float_t				eleSigmaIEtaIEta[11];
 Float_t				eleSigmaIEtaIPhi[11];
 Float_t				eleSigmaIPhiIPhi[11];
 Float_t				eleEmax[11];
 Float_t				eleE1x5[11];
 Float_t				eleE3x3[11];
 Float_t				eleE5x5[11];
 Float_t				eleE2x5Max[11];
 Float_t				eleRegrE[11];
 Float_t				eleRegrEerr[11];
 Float_t				elePhoRegrE[11];
 Float_t				elePhoRegrEerr[11];
 Float_t				eleSeedTime[11];
 Int_t				eleRecoFlag[11];
 Int_t				elePos[11];
 Int_t				eleGenIndex[11];
 Int_t				eleGenGMomPID[11];
 Int_t				eleGenMomPID[11];
 Float_t				eleGenMomPt[11];
 Float_t				eleIsoTrkDR03[11];
 Float_t				eleIsoEcalDR03[11];
 Float_t				eleIsoHcalDR03[11];
 Float_t				eleIsoHcalDR0312[11];
 Float_t				eleIsoTrkDR04[11];
 Float_t				eleIsoEcalDR04[11];
 Float_t				eleIsoHcalDR04[11];
 Float_t				eleIsoHcalDR0412[11];
 Float_t				eleModIsoTrk[11];
 Float_t				eleModIsoEcal[11];
 Float_t				eleModIsoHcal[11];
 Int_t				eleMissHits[11];
 Float_t				eleConvDist[11];
 Float_t				eleConvDcot[11];
 Int_t				eleConvVtxFit[11];
 Float_t				eleIP3D[11];
 Float_t				eleIP3DErr[11];
 Float_t				eleIDMVANonTrig[11];
 Float_t				eleIDMVATrig[11];
 Float_t				eleIDMVATrigIDIso[11];
 Float_t				elePFChIso03[11];
 Float_t				elePFPhoIso03[11];
 Float_t				elePFNeuIso03[11];
 Float_t				elePFChIso04[11];
 Float_t				elePFPhoIso04[11];
 Float_t				elePFNeuIso04[11];
 Float_t				eleESEffSigmaRR[11][3];
 Int_t				phoTrg[12][8];
 Int_t				phoTrgFilter[12][50];
 Bool_t				phoIsPhoton[12];
 Float_t				phoSCPos[12][3];
 Float_t				phoCaloPos[12][3];
 Float_t				phoE[12];
 Float_t				phoEt[12];
 Float_t				phoEta[12];
 Float_t				phoVtx[12][3];
 Float_t				phoPhi[12];
 Float_t				phoR9[12];
 Float_t				phoTrkIsoHollowDR03[12];
 Float_t				phoEcalIsoDR03[12];
 Float_t				phoHcalIsoDR03[12];
 Float_t				phoHcalIsoDR0312[12];
 Float_t				phoTrkIsoHollowDR04[12];
 Float_t				phoCiCdRtoTrk[12];
 Float_t				phoEcalIsoDR04[12];
 Float_t				phoHcalIsoDR04[12];
 Float_t				phoHcalIsoDR0412[12];
 Float_t				phoHoverE[12];
 Float_t				phoHoverE12[12];
 Int_t				phoEleVeto[12];
 Float_t				phoSigmaIEtaIEta[12];
 Float_t				phoSigmaIEtaIPhi[12];
 Float_t				phoSigmaIPhiIPhi[12];
 Float_t				phoCiCPF4phopfIso03[12];
 Float_t				phoCiCPF4phopfIso04[12];
 Float_t				phoEmax[12];
 Float_t				phoE3x3[12];
 Float_t				phoE3x1[12];
 Float_t				phoE1x3[12];
 Float_t				phoE5x5[12];
 Float_t				phoE1x5[12];
 Float_t				phoE2x2[12];
 Float_t				phoE2x5Max[12];
 Float_t				phoPFChIso[12];
 Float_t				phoPFPhoIso[12];
 Float_t				phoPFNeuIso[12];
 Float_t				phoSCRChIso[12];
 Float_t				phoSCRPhoIso[12];
 Float_t				phoSCRNeuIso[12];
 Float_t				phoRegrE[12];
 Float_t				phoRegrEerr[12];
 Float_t				phoSeedTime[12];
 Int_t				phoSeedDetId1[12];
 Int_t				phoSeedDetId2[12];
 Float_t				phoLICTD[12];
 Int_t				phoRecoFlag[12];
 Int_t				phoPos[12];
 Int_t				phoGenIndex[12];
 Int_t				phoGenGMomPID[12];
 Int_t				phoGenMomPID[12];
 Float_t				phoGenMomPt[12];
 Float_t				phoSCE[12];
 Float_t				phoSCRawE[12];
 Float_t				phoESEn[12];
 Float_t				phoSCEt[12];
 Float_t				phoSCEta[12];
 Float_t				phoSCPhi[12];
 Float_t				phoSCEtaWidth[12];
 Float_t				phoSCPhiWidth[12];
 Float_t				phoSCBrem[12];
 Int_t				phoOverlap[12];
 Int_t				phohasPixelSeed[12];
 Int_t				pho_hasConvPf[12];
 Int_t				pho_hasSLConvPf[12];
 Float_t				pho_pfconvVtxZ[12];
 Float_t				pho_pfconvVtxZErr[12];
 Int_t				pho_nSLConv[12];
 Float_t				pho_pfSLConvPos[12][20][3];
 Float_t				pho_pfSLConvVtxZ[12][20];
 Int_t				phoIsConv[12];
 Int_t				phoNConv[12];
 Float_t				phoConvInvMass[12];
 Float_t				phoConvCotTheta[12];
 Float_t				phoConvEoverP[12];
 Float_t				phoConvZofPVfromTrks[12];
 Float_t				phoConvMinDist[12];
 Float_t				phoConvdPhiAtVtx[12];
 Float_t				phoConvdPhiAtCalo[12];
 Float_t				phoConvdEtaAtCalo[12];
 Float_t				phoConvTrkd0[12][2];
 Float_t				phoConvTrkPin[12][2];
 Float_t				phoConvTrkPout[12][2];
 Float_t				phoConvTrkdz[12][2];
 Float_t				phoConvTrkdzErr[12][2];
 Float_t				phoConvChi2[12];
 Float_t				phoConvChi2Prob[12];
 Int_t				phoConvNTrks[12];
 Float_t				phoConvCharge[12][2];
 Float_t				phoConvValidVtx[12];
 Float_t				phoConvLikeLihood[12];
 Float_t				phoConvP4[12][4];
 Float_t				phoConvVtx[12][3];
 Float_t				phoConvVtxErr[12][3];
 Float_t				phoConvPairMomentum[12][3];
 Float_t				phoConvRefittedMomentum[12][3];
 Int_t				SingleLegConv[12];
 Float_t				phoPFConvVtx[12][3];
 Float_t				phoPFConvMom[12][3];
 Float_t				phoESEffSigmaRR[12][3];
 Int_t				muTrg[16][10];
 Float_t				muEta[16];
 Float_t				muPhi[16];
 Int_t				muCharge[16];
 Float_t				muPt[16];
 Float_t				muPz[16];
 Float_t				muVtx[16][3];
 Float_t				muVtxGlb[16][3];
 Int_t				muGenIndex[16];
 Float_t				mucktPt[16];
 Float_t				mucktPtErr[16];
 Float_t				mucktEta[16];
 Float_t				mucktPhi[16];
 Float_t				mucktdxy[16];
 Float_t				mucktdz[16];
 Float_t				muIsoTrk[16];
 Float_t				muIsoCalo[16];
 Float_t				muIsoEcal[16];
 Float_t				muIsoHcal[16];
 Float_t				muChi2NDF[16];
 Float_t				muInnerChi2NDF[16];
 Float_t				muPFIsoR04_CH[16];
 Float_t				muPFIsoR04_NH[16];
 Float_t				muPFIsoR04_Pho[16];
 Float_t				muPFIsoR04_PU[16];
 Float_t				muPFIsoR04_CPart[16];
 Float_t				muPFIsoR04_NHHT[16];
 Float_t				muPFIsoR04_PhoHT[16];
 Float_t				muPFIsoR03_CH[16];
 Float_t				muPFIsoR03_NH[16];
 Float_t				muPFIsoR03_Pho[16];
 Float_t				muPFIsoR03_PU[16];
 Float_t				muPFIsoR03_CPart[16];
 Float_t				muPFIsoR03_NHHT[16];
 Float_t				muPFIsoR03_PhoHT[16];
 Int_t				muType[16];
 Float_t				muD0[16];
 Float_t				muDz[16];
 Float_t				muD0GV[16];
 Float_t				muDzGV[16];
 Float_t				muInnerD0[16];
 Float_t				muInnerDz[16];
 Float_t				muInnerD0GV[16];
 Float_t				muInnerDzGV[16];
 Float_t				muInnerPt[16];
 Float_t				muInnerPtErr[16];
 Int_t				muNumberOfValidTrkLayers[16];
 Int_t				muNumberOfValidTrkHits[16];
 Int_t				muNumberOfValidPixelLayers[16];
 Int_t				muNumberOfValidPixelHits[16];
 Int_t				muNumberOfValidMuonHits[16];
 Int_t				muStations[16];
 Int_t				muChambers[16];
 Float_t				muIP3D[16];
 Float_t				muIP3DErr[16];
 Float_t				PFPhoEt[50];
 Float_t				PFPhoEta[50];
 Float_t				PFPhoPhi[50];
 Int_t				PFPhoType[50];
 Float_t				PFPhoIso[50];
 Float_t				rho25;
 Float_t				rho25_neu;
 Float_t				rho25_muPFiso;
 Float_t				rho25_elePFiso;
 Float_t				rho2011;
 Float_t				rho2012;
 Int_t				jetTrg[22][14];
 Float_t				jetEn[22];
 Float_t				jetPt[22];
 Float_t				jetEta[22];
 Float_t				jetPhi[22];
 Float_t				jetCharge[22];
 Float_t				jetEt[22];
 Float_t				jetRawPt[22];
 Float_t				jetRawEn[22];
 Float_t				jetArea[22];
 Float_t				jetCHF[22];
 Float_t				jetNHF[22];
 Float_t				jetCEF[22];
 Float_t				jetNEF[22];
 Int_t				jetNCH[22];
 Float_t				jetHFHAE[22];
 Float_t				jetHFEME[22];
 Int_t				jetNConstituents[22];
 Float_t				jetCombinedSecondaryVtxBJetTags[22];
 Float_t				jetCombinedSecondaryVtxMVABJetTags[22];
 Float_t				jetJetProbabilityBJetTags[22];
 Float_t				jetJetBProbabilityBJetTags[22];
 Float_t				jetTrackCountingHighPurBJetTags[22];
 Float_t				jetBetaStar[22][100];
 Bool_t				jetPFLooseId[22];
 Float_t				jetDRMean[22];
 Float_t				jetDR2Mean[22];
 Float_t				jetDZ[22];
 Float_t				jetFrac01[22];
 Float_t				jetFrac02[22];
 Float_t				jetFrac03[22];
 Float_t				jetFrac04[22];
 Float_t				jetFrac05[22];
 Float_t				jetFrac06[22];
 Float_t				jetFrac07[22];
 Float_t				jetBeta[22];
 Float_t				jetBetaStarCMG[22];
 Float_t				jetBetaStarClassic[22];
 Float_t				jetBetaExt[22][100];
 Float_t				jetNNeutrals[22];
 Float_t				jetNCharged[22];
 Float_t				jetMVAs[22][4];
 Int_t				jetWPLevels[22][4];
 Float_t				jetMt[22];
 Float_t				jetJECUnc[22];
 Float_t				jetLeadTrackPt[22];
 Float_t				jetVtxPt[22];
 Float_t				jetVtxMass[22];
 Float_t				jetVtx3dL[22];
 Float_t				jetVtx3deL[22];
 Float_t				jetSoftLeptPt[22];
 Float_t				jetSoftLeptPtRel[22];
 Float_t				jetSoftLeptdR[22];
 Float_t				jetSoftLeptIdlooseMu[22];
 Float_t				jetSoftLeptIdEle95[22];
 Float_t				jetDPhiMETJet[22];
 Float_t				jetPuJetIdL[22];
 Float_t				jetPuJetIdM[22];
 Float_t				jetPuJetIdT[22];
 Int_t				jetPartonID[22];
 Int_t				jetGenJetIndex[22];
 Float_t				jetGenJetEn[22];
 Float_t				jetGenJetPt[22];
 Float_t				jetGenJetEta[22];
 Float_t				jetGenJetPhi[22];
 Int_t				jetGenPartonID[22];
 Float_t				jetGenEn[22];
 Float_t				jetGenPt[22];
 Float_t				jetGenEta[22];
 Float_t				jetGenPhi[22];
 Float_t				convVtx[156][3];
 Float_t				convVtxErr[156][3];
 Float_t				convPairMomentum[156][3];
 Float_t				convRefittedMomentum[156][3];
 Int_t				convNTracks[156];
 Float_t				convPairInvMass[156];
 Float_t				convPairCotThetaSep[156];
 Float_t				convEoverP[156];
 Float_t				convDistOfMinApproach[156];
 Float_t				convDPhiTrksAtVtx[156];
 Float_t				convDPhiTrksAtEcal[156];
 Float_t				convDEtaTrksAtEcal[156];
 Float_t				convDxy[156];
 Float_t				convDz[156];
 Float_t				convLxy[156];
 Float_t				convLz[156];
 Float_t				convZofPrimVtxFromTrks[156];
 Int_t				convNHitsBeforeVtx[156][2];
 Int_t				convNSharedHits[156];
 Int_t				convValidVtx[156];
 Float_t				convMVALikelihood[156];
 Float_t				convChi2[156];
 Float_t				convChi2Probability[156];
 Float_t				convTk1Dz[156];
 Float_t				convTk2Dz[156];
 Float_t				convTk1DzErr[156];
 Float_t				convTk2DzErr[156];
 Int_t				convCh1Ch2[156];
 Float_t				convTk1D0[156];
 Float_t				convTk1Pout[156];
 Float_t				convTk1Pin[156];
 Float_t				convTk2D0[156];
 Float_t				convTk2Pout[156];
 Float_t				convTk2Pin[156];
};
namespace OUT {
 Int_t				nVtxBS;
 Float_t				pfMET;
 Float_t				pfMETPhi;
 Float_t				pfMETsumEt;
 Float_t				pfMETmEtSig;
 Float_t				pfMETSig;
 Float_t				recoPfMET;
 Float_t				recoPfMETPhi;
 Float_t				recoPfMETsumEt;
 Float_t				recoPfMETmEtSig;
 Float_t				recoPfMETSig;
};
void InitINTree( TChain * tree) {

  tree->SetBranchAddress("nHLT", &IN::nHLT);
  tree->SetBranchAddress("nVtx", &IN::nVtx);
  tree->SetBranchAddress("nVtxBS", &IN::nVtxBS);
  tree->SetBranchAddress("nMC", &IN::nMC);
  tree->SetBranchAddress("nPUInfo", &IN::nPUInfo);
  tree->SetBranchAddress("nEle", &IN::nEle);
  tree->SetBranchAddress("nPho", &IN::nPho);
  tree->SetBranchAddress("nMu", &IN::nMu);
  tree->SetBranchAddress("nPFPho", &IN::nPFPho);
  tree->SetBranchAddress("nJet", &IN::nJet);
  tree->SetBranchAddress("nConv", &IN::nConv);
  tree->SetBranchAddress("nLowPtJet", &IN::nLowPtJet);
  tree->SetBranchAddress("run", &IN::run);
  tree->SetBranchAddress("event", &IN::event);
  tree->SetBranchAddress("lumis", &IN::lumis);
  tree->SetBranchAddress("isData", &IN::isData);
  tree->SetBranchAddress("HLT", &IN::HLT);
  tree->SetBranchAddress("HLTIndex", &IN::HLTIndex);
  tree->SetBranchAddress("bspotPos", &IN::bspotPos);
  tree->SetBranchAddress("vtx", &IN::vtx);
  tree->SetBranchAddress("IsVtxGood", &IN::IsVtxGood);
  tree->SetBranchAddress("nGoodVtx", &IN::nGoodVtx);
  tree->SetBranchAddress("vtxbs", &IN::vtxbs);
  tree->SetBranchAddress("pdf", &IN::pdf);
  tree->SetBranchAddress("pthat", &IN::pthat);
  tree->SetBranchAddress("processID", &IN::processID);
  tree->SetBranchAddress("mcPID", &IN::mcPID);
  tree->SetBranchAddress("mcPt", &IN::mcPt);
  tree->SetBranchAddress("mcEta", &IN::mcEta);
  tree->SetBranchAddress("mcPhi", &IN::mcPhi);
  tree->SetBranchAddress("mcE", &IN::mcE);
  tree->SetBranchAddress("mcGMomPID", &IN::mcGMomPID);
  tree->SetBranchAddress("mcMomPID", &IN::mcMomPID);
  tree->SetBranchAddress("mcMomPt", &IN::mcMomPt);
  tree->SetBranchAddress("mcMomMass", &IN::mcMomMass);
  tree->SetBranchAddress("mcMomEta", &IN::mcMomEta);
  tree->SetBranchAddress("mcMomPhi", &IN::mcMomPhi);
  tree->SetBranchAddress("mcIndex", &IN::mcIndex);
  tree->SetBranchAddress("mcDecayType", &IN::mcDecayType);
  tree->SetBranchAddress("mcParentage", &IN::mcParentage);
  tree->SetBranchAddress("mcStatus", &IN::mcStatus);
  tree->SetBranchAddress("genMET", &IN::genMET);
  tree->SetBranchAddress("genMETPhi", &IN::genMETPhi);
  tree->SetBranchAddress("nPU", &IN::nPU);
  tree->SetBranchAddress("puBX", &IN::puBX);
  tree->SetBranchAddress("puTrue", &IN::puTrue);
  tree->SetBranchAddress("pfMET", &IN::pfMET);
  tree->SetBranchAddress("pfMETPhi", &IN::pfMETPhi);
  tree->SetBranchAddress("pfMETsumEt", &IN::pfMETsumEt);
  tree->SetBranchAddress("pfMETmEtSig", &IN::pfMETmEtSig);
  tree->SetBranchAddress("pfMETSig", &IN::pfMETSig);
  tree->SetBranchAddress("recoPfMET", &IN::recoPfMET);
  tree->SetBranchAddress("recoPfMETPhi", &IN::recoPfMETPhi);
  tree->SetBranchAddress("recoPfMETsumEt", &IN::recoPfMETsumEt);
  tree->SetBranchAddress("recoPfMETmEtSig", &IN::recoPfMETmEtSig);
  tree->SetBranchAddress("recoPfMETSig", &IN::recoPfMETSig);
  tree->SetBranchAddress("trkMETxPV", &IN::trkMETxPV);
  tree->SetBranchAddress("trkMETyPV", &IN::trkMETyPV);
  tree->SetBranchAddress("trkMETPhiPV", &IN::trkMETPhiPV);
  tree->SetBranchAddress("trkMETPV", &IN::trkMETPV);
  tree->SetBranchAddress("trkMETx", &IN::trkMETx);
  tree->SetBranchAddress("trkMETy", &IN::trkMETy);
  tree->SetBranchAddress("trkMETPhi", &IN::trkMETPhi);
  tree->SetBranchAddress("trkMET", &IN::trkMET);
  tree->SetBranchAddress("metFilters", &IN::metFilters);
  tree->SetBranchAddress("eleTrg", &IN::eleTrg);
  tree->SetBranchAddress("eleClass", &IN::eleClass);
  tree->SetBranchAddress("eleIsEcalDriven", &IN::eleIsEcalDriven);
  tree->SetBranchAddress("eleCharge", &IN::eleCharge);
  tree->SetBranchAddress("eleEn", &IN::eleEn);
  tree->SetBranchAddress("eleEcalEn", &IN::eleEcalEn);
  tree->SetBranchAddress("eleSCRawEn", &IN::eleSCRawEn);
  tree->SetBranchAddress("eleSCEn", &IN::eleSCEn);
  tree->SetBranchAddress("eleESEn", &IN::eleESEn);
  tree->SetBranchAddress("elePt", &IN::elePt);
  tree->SetBranchAddress("eleEta", &IN::eleEta);
  tree->SetBranchAddress("elePhi", &IN::elePhi);
  tree->SetBranchAddress("eleSCEta", &IN::eleSCEta);
  tree->SetBranchAddress("eleSCPhi", &IN::eleSCPhi);
  tree->SetBranchAddress("eleSCEtaWidth", &IN::eleSCEtaWidth);
  tree->SetBranchAddress("eleSCPhiWidth", &IN::eleSCPhiWidth);
  tree->SetBranchAddress("eleVtx", &IN::eleVtx);
  tree->SetBranchAddress("eleD0", &IN::eleD0);
  tree->SetBranchAddress("eleDz", &IN::eleDz);
  tree->SetBranchAddress("eleD0GV", &IN::eleD0GV);
  tree->SetBranchAddress("eleDzGV", &IN::eleDzGV);
  tree->SetBranchAddress("eleHoverE", &IN::eleHoverE);
  tree->SetBranchAddress("eleHoverE12", &IN::eleHoverE12);
  tree->SetBranchAddress("eleEoverP", &IN::eleEoverP);
  tree->SetBranchAddress("elePin", &IN::elePin);
  tree->SetBranchAddress("elePout", &IN::elePout);
  tree->SetBranchAddress("eleTrkMomErr", &IN::eleTrkMomErr);
  tree->SetBranchAddress("eleBrem", &IN::eleBrem);
  tree->SetBranchAddress("eledEtaAtVtx", &IN::eledEtaAtVtx);
  tree->SetBranchAddress("eledPhiAtVtx", &IN::eledPhiAtVtx);
  tree->SetBranchAddress("eleSigmaIEtaIEta", &IN::eleSigmaIEtaIEta);
  tree->SetBranchAddress("eleSigmaIEtaIPhi", &IN::eleSigmaIEtaIPhi);
  tree->SetBranchAddress("eleSigmaIPhiIPhi", &IN::eleSigmaIPhiIPhi);
  tree->SetBranchAddress("eleEmax", &IN::eleEmax);
  tree->SetBranchAddress("eleE1x5", &IN::eleE1x5);
  tree->SetBranchAddress("eleE3x3", &IN::eleE3x3);
  tree->SetBranchAddress("eleE5x5", &IN::eleE5x5);
  tree->SetBranchAddress("eleE2x5Max", &IN::eleE2x5Max);
  tree->SetBranchAddress("eleRegrE", &IN::eleRegrE);
  tree->SetBranchAddress("eleRegrEerr", &IN::eleRegrEerr);
  tree->SetBranchAddress("elePhoRegrE", &IN::elePhoRegrE);
  tree->SetBranchAddress("elePhoRegrEerr", &IN::elePhoRegrEerr);
  tree->SetBranchAddress("eleSeedTime", &IN::eleSeedTime);
  tree->SetBranchAddress("eleRecoFlag", &IN::eleRecoFlag);
  tree->SetBranchAddress("elePos", &IN::elePos);
  tree->SetBranchAddress("eleGenIndex", &IN::eleGenIndex);
  tree->SetBranchAddress("eleGenGMomPID", &IN::eleGenGMomPID);
  tree->SetBranchAddress("eleGenMomPID", &IN::eleGenMomPID);
  tree->SetBranchAddress("eleGenMomPt", &IN::eleGenMomPt);
  tree->SetBranchAddress("eleIsoTrkDR03", &IN::eleIsoTrkDR03);
  tree->SetBranchAddress("eleIsoEcalDR03", &IN::eleIsoEcalDR03);
  tree->SetBranchAddress("eleIsoHcalDR03", &IN::eleIsoHcalDR03);
  tree->SetBranchAddress("eleIsoHcalDR0312", &IN::eleIsoHcalDR0312);
  tree->SetBranchAddress("eleIsoTrkDR04", &IN::eleIsoTrkDR04);
  tree->SetBranchAddress("eleIsoEcalDR04", &IN::eleIsoEcalDR04);
  tree->SetBranchAddress("eleIsoHcalDR04", &IN::eleIsoHcalDR04);
  tree->SetBranchAddress("eleIsoHcalDR0412", &IN::eleIsoHcalDR0412);
  tree->SetBranchAddress("eleModIsoTrk", &IN::eleModIsoTrk);
  tree->SetBranchAddress("eleModIsoEcal", &IN::eleModIsoEcal);
  tree->SetBranchAddress("eleModIsoHcal", &IN::eleModIsoHcal);
  tree->SetBranchAddress("eleMissHits", &IN::eleMissHits);
  tree->SetBranchAddress("eleConvDist", &IN::eleConvDist);
  tree->SetBranchAddress("eleConvDcot", &IN::eleConvDcot);
  tree->SetBranchAddress("eleConvVtxFit", &IN::eleConvVtxFit);
  tree->SetBranchAddress("eleIP3D", &IN::eleIP3D);
  tree->SetBranchAddress("eleIP3DErr", &IN::eleIP3DErr);
  tree->SetBranchAddress("eleIDMVANonTrig", &IN::eleIDMVANonTrig);
  tree->SetBranchAddress("eleIDMVATrig", &IN::eleIDMVATrig);
  tree->SetBranchAddress("eleIDMVATrigIDIso", &IN::eleIDMVATrigIDIso);
  tree->SetBranchAddress("elePFChIso03", &IN::elePFChIso03);
  tree->SetBranchAddress("elePFPhoIso03", &IN::elePFPhoIso03);
  tree->SetBranchAddress("elePFNeuIso03", &IN::elePFNeuIso03);
  tree->SetBranchAddress("elePFChIso04", &IN::elePFChIso04);
  tree->SetBranchAddress("elePFPhoIso04", &IN::elePFPhoIso04);
  tree->SetBranchAddress("elePFNeuIso04", &IN::elePFNeuIso04);
  tree->SetBranchAddress("eleESEffSigmaRR", &IN::eleESEffSigmaRR);
  tree->SetBranchAddress("phoTrg", &IN::phoTrg);
  tree->SetBranchAddress("phoTrgFilter", &IN::phoTrgFilter);
  tree->SetBranchAddress("phoIsPhoton", &IN::phoIsPhoton);
  tree->SetBranchAddress("phoSCPos", &IN::phoSCPos);
  tree->SetBranchAddress("phoCaloPos", &IN::phoCaloPos);
  tree->SetBranchAddress("phoE", &IN::phoE);
  tree->SetBranchAddress("phoEt", &IN::phoEt);
  tree->SetBranchAddress("phoEta", &IN::phoEta);
  tree->SetBranchAddress("phoVtx", &IN::phoVtx);
  tree->SetBranchAddress("phoPhi", &IN::phoPhi);
  tree->SetBranchAddress("phoR9", &IN::phoR9);
  tree->SetBranchAddress("phoTrkIsoHollowDR03", &IN::phoTrkIsoHollowDR03);
  tree->SetBranchAddress("phoEcalIsoDR03", &IN::phoEcalIsoDR03);
  tree->SetBranchAddress("phoHcalIsoDR03", &IN::phoHcalIsoDR03);
  tree->SetBranchAddress("phoHcalIsoDR0312", &IN::phoHcalIsoDR0312);
  tree->SetBranchAddress("phoTrkIsoHollowDR04", &IN::phoTrkIsoHollowDR04);
  tree->SetBranchAddress("phoCiCdRtoTrk", &IN::phoCiCdRtoTrk);
  tree->SetBranchAddress("phoEcalIsoDR04", &IN::phoEcalIsoDR04);
  tree->SetBranchAddress("phoHcalIsoDR04", &IN::phoHcalIsoDR04);
  tree->SetBranchAddress("phoHcalIsoDR0412", &IN::phoHcalIsoDR0412);
  tree->SetBranchAddress("phoHoverE", &IN::phoHoverE);
  tree->SetBranchAddress("phoHoverE12", &IN::phoHoverE12);
  tree->SetBranchAddress("phoEleVeto", &IN::phoEleVeto);
  tree->SetBranchAddress("phoSigmaIEtaIEta", &IN::phoSigmaIEtaIEta);
  tree->SetBranchAddress("phoSigmaIEtaIPhi", &IN::phoSigmaIEtaIPhi);
  tree->SetBranchAddress("phoSigmaIPhiIPhi", &IN::phoSigmaIPhiIPhi);
  tree->SetBranchAddress("phoCiCPF4phopfIso03", &IN::phoCiCPF4phopfIso03);
  tree->SetBranchAddress("phoCiCPF4phopfIso04", &IN::phoCiCPF4phopfIso04);
  tree->SetBranchAddress("phoEmax", &IN::phoEmax);
  tree->SetBranchAddress("phoE3x3", &IN::phoE3x3);
  tree->SetBranchAddress("phoE3x1", &IN::phoE3x1);
  tree->SetBranchAddress("phoE1x3", &IN::phoE1x3);
  tree->SetBranchAddress("phoE5x5", &IN::phoE5x5);
  tree->SetBranchAddress("phoE1x5", &IN::phoE1x5);
  tree->SetBranchAddress("phoE2x2", &IN::phoE2x2);
  tree->SetBranchAddress("phoE2x5Max", &IN::phoE2x5Max);
  tree->SetBranchAddress("phoPFChIso", &IN::phoPFChIso);
  tree->SetBranchAddress("phoPFPhoIso", &IN::phoPFPhoIso);
  tree->SetBranchAddress("phoPFNeuIso", &IN::phoPFNeuIso);
  tree->SetBranchAddress("phoSCRChIso", &IN::phoSCRChIso);
  tree->SetBranchAddress("phoSCRPhoIso", &IN::phoSCRPhoIso);
  tree->SetBranchAddress("phoSCRNeuIso", &IN::phoSCRNeuIso);
  tree->SetBranchAddress("phoRegrE", &IN::phoRegrE);
  tree->SetBranchAddress("phoRegrEerr", &IN::phoRegrEerr);
  tree->SetBranchAddress("phoSeedTime", &IN::phoSeedTime);
  tree->SetBranchAddress("phoSeedDetId1", &IN::phoSeedDetId1);
  tree->SetBranchAddress("phoSeedDetId2", &IN::phoSeedDetId2);
  tree->SetBranchAddress("phoLICTD", &IN::phoLICTD);
  tree->SetBranchAddress("phoRecoFlag", &IN::phoRecoFlag);
  tree->SetBranchAddress("phoPos", &IN::phoPos);
  tree->SetBranchAddress("phoGenIndex", &IN::phoGenIndex);
  tree->SetBranchAddress("phoGenGMomPID", &IN::phoGenGMomPID);
  tree->SetBranchAddress("phoGenMomPID", &IN::phoGenMomPID);
  tree->SetBranchAddress("phoGenMomPt", &IN::phoGenMomPt);
  tree->SetBranchAddress("phoSCE", &IN::phoSCE);
  tree->SetBranchAddress("phoSCRawE", &IN::phoSCRawE);
  tree->SetBranchAddress("phoESEn", &IN::phoESEn);
  tree->SetBranchAddress("phoSCEt", &IN::phoSCEt);
  tree->SetBranchAddress("phoSCEta", &IN::phoSCEta);
  tree->SetBranchAddress("phoSCPhi", &IN::phoSCPhi);
  tree->SetBranchAddress("phoSCEtaWidth", &IN::phoSCEtaWidth);
  tree->SetBranchAddress("phoSCPhiWidth", &IN::phoSCPhiWidth);
  tree->SetBranchAddress("phoSCBrem", &IN::phoSCBrem);
  tree->SetBranchAddress("phoOverlap", &IN::phoOverlap);
  tree->SetBranchAddress("phohasPixelSeed", &IN::phohasPixelSeed);
  tree->SetBranchAddress("pho_hasConvPf", &IN::pho_hasConvPf);
  tree->SetBranchAddress("pho_hasSLConvPf", &IN::pho_hasSLConvPf);
  tree->SetBranchAddress("pho_pfconvVtxZ", &IN::pho_pfconvVtxZ);
  tree->SetBranchAddress("pho_pfconvVtxZErr", &IN::pho_pfconvVtxZErr);
  tree->SetBranchAddress("pho_nSLConv", &IN::pho_nSLConv);
  tree->SetBranchAddress("pho_pfSLConvPos", &IN::pho_pfSLConvPos);
  tree->SetBranchAddress("pho_pfSLConvVtxZ", &IN::pho_pfSLConvVtxZ);
  tree->SetBranchAddress("phoIsConv", &IN::phoIsConv);
  tree->SetBranchAddress("phoNConv", &IN::phoNConv);
  tree->SetBranchAddress("phoConvInvMass", &IN::phoConvInvMass);
  tree->SetBranchAddress("phoConvCotTheta", &IN::phoConvCotTheta);
  tree->SetBranchAddress("phoConvEoverP", &IN::phoConvEoverP);
  tree->SetBranchAddress("phoConvZofPVfromTrks", &IN::phoConvZofPVfromTrks);
  tree->SetBranchAddress("phoConvMinDist", &IN::phoConvMinDist);
  tree->SetBranchAddress("phoConvdPhiAtVtx", &IN::phoConvdPhiAtVtx);
  tree->SetBranchAddress("phoConvdPhiAtCalo", &IN::phoConvdPhiAtCalo);
  tree->SetBranchAddress("phoConvdEtaAtCalo", &IN::phoConvdEtaAtCalo);
  tree->SetBranchAddress("phoConvTrkd0", &IN::phoConvTrkd0);
  tree->SetBranchAddress("phoConvTrkPin", &IN::phoConvTrkPin);
  tree->SetBranchAddress("phoConvTrkPout", &IN::phoConvTrkPout);
  tree->SetBranchAddress("phoConvTrkdz", &IN::phoConvTrkdz);
  tree->SetBranchAddress("phoConvTrkdzErr", &IN::phoConvTrkdzErr);
  tree->SetBranchAddress("phoConvChi2", &IN::phoConvChi2);
  tree->SetBranchAddress("phoConvChi2Prob", &IN::phoConvChi2Prob);
  tree->SetBranchAddress("phoConvNTrks", &IN::phoConvNTrks);
  tree->SetBranchAddress("phoConvCharge", &IN::phoConvCharge);
  tree->SetBranchAddress("phoConvValidVtx", &IN::phoConvValidVtx);
  tree->SetBranchAddress("phoConvLikeLihood", &IN::phoConvLikeLihood);
  tree->SetBranchAddress("phoConvP4", &IN::phoConvP4);
  tree->SetBranchAddress("phoConvVtx", &IN::phoConvVtx);
  tree->SetBranchAddress("phoConvVtxErr", &IN::phoConvVtxErr);
  tree->SetBranchAddress("phoConvPairMomentum", &IN::phoConvPairMomentum);
  tree->SetBranchAddress("phoConvRefittedMomentum", &IN::phoConvRefittedMomentum);
  tree->SetBranchAddress("SingleLegConv", &IN::SingleLegConv);
  tree->SetBranchAddress("phoPFConvVtx", &IN::phoPFConvVtx);
  tree->SetBranchAddress("phoPFConvMom", &IN::phoPFConvMom);
  tree->SetBranchAddress("phoESEffSigmaRR", &IN::phoESEffSigmaRR);
  tree->SetBranchAddress("muTrg", &IN::muTrg);
  tree->SetBranchAddress("muEta", &IN::muEta);
  tree->SetBranchAddress("muPhi", &IN::muPhi);
  tree->SetBranchAddress("muCharge", &IN::muCharge);
  tree->SetBranchAddress("muPt", &IN::muPt);
  tree->SetBranchAddress("muPz", &IN::muPz);
  tree->SetBranchAddress("muVtx", &IN::muVtx);
  tree->SetBranchAddress("muVtxGlb", &IN::muVtxGlb);
  tree->SetBranchAddress("muGenIndex", &IN::muGenIndex);
  tree->SetBranchAddress("mucktPt", &IN::mucktPt);
  tree->SetBranchAddress("mucktPtErr", &IN::mucktPtErr);
  tree->SetBranchAddress("mucktEta", &IN::mucktEta);
  tree->SetBranchAddress("mucktPhi", &IN::mucktPhi);
  tree->SetBranchAddress("mucktdxy", &IN::mucktdxy);
  tree->SetBranchAddress("mucktdz", &IN::mucktdz);
  tree->SetBranchAddress("muIsoTrk", &IN::muIsoTrk);
  tree->SetBranchAddress("muIsoCalo", &IN::muIsoCalo);
  tree->SetBranchAddress("muIsoEcal", &IN::muIsoEcal);
  tree->SetBranchAddress("muIsoHcal", &IN::muIsoHcal);
  tree->SetBranchAddress("muChi2NDF", &IN::muChi2NDF);
  tree->SetBranchAddress("muInnerChi2NDF", &IN::muInnerChi2NDF);
  tree->SetBranchAddress("muPFIsoR04_CH", &IN::muPFIsoR04_CH);
  tree->SetBranchAddress("muPFIsoR04_NH", &IN::muPFIsoR04_NH);
  tree->SetBranchAddress("muPFIsoR04_Pho", &IN::muPFIsoR04_Pho);
  tree->SetBranchAddress("muPFIsoR04_PU", &IN::muPFIsoR04_PU);
  tree->SetBranchAddress("muPFIsoR04_CPart", &IN::muPFIsoR04_CPart);
  tree->SetBranchAddress("muPFIsoR04_NHHT", &IN::muPFIsoR04_NHHT);
  tree->SetBranchAddress("muPFIsoR04_PhoHT", &IN::muPFIsoR04_PhoHT);
  tree->SetBranchAddress("muPFIsoR03_CH", &IN::muPFIsoR03_CH);
  tree->SetBranchAddress("muPFIsoR03_NH", &IN::muPFIsoR03_NH);
  tree->SetBranchAddress("muPFIsoR03_Pho", &IN::muPFIsoR03_Pho);
  tree->SetBranchAddress("muPFIsoR03_PU", &IN::muPFIsoR03_PU);
  tree->SetBranchAddress("muPFIsoR03_CPart", &IN::muPFIsoR03_CPart);
  tree->SetBranchAddress("muPFIsoR03_NHHT", &IN::muPFIsoR03_NHHT);
  tree->SetBranchAddress("muPFIsoR03_PhoHT", &IN::muPFIsoR03_PhoHT);
  tree->SetBranchAddress("muType", &IN::muType);
  tree->SetBranchAddress("muD0", &IN::muD0);
  tree->SetBranchAddress("muDz", &IN::muDz);
  tree->SetBranchAddress("muD0GV", &IN::muD0GV);
  tree->SetBranchAddress("muDzGV", &IN::muDzGV);
  tree->SetBranchAddress("muInnerD0", &IN::muInnerD0);
  tree->SetBranchAddress("muInnerDz", &IN::muInnerDz);
  tree->SetBranchAddress("muInnerD0GV", &IN::muInnerD0GV);
  tree->SetBranchAddress("muInnerDzGV", &IN::muInnerDzGV);
  tree->SetBranchAddress("muInnerPt", &IN::muInnerPt);
  tree->SetBranchAddress("muInnerPtErr", &IN::muInnerPtErr);
  tree->SetBranchAddress("muNumberOfValidTrkLayers", &IN::muNumberOfValidTrkLayers);
  tree->SetBranchAddress("muNumberOfValidTrkHits", &IN::muNumberOfValidTrkHits);
  tree->SetBranchAddress("muNumberOfValidPixelLayers", &IN::muNumberOfValidPixelLayers);
  tree->SetBranchAddress("muNumberOfValidPixelHits", &IN::muNumberOfValidPixelHits);
  tree->SetBranchAddress("muNumberOfValidMuonHits", &IN::muNumberOfValidMuonHits);
  tree->SetBranchAddress("muStations", &IN::muStations);
  tree->SetBranchAddress("muChambers", &IN::muChambers);
  tree->SetBranchAddress("muIP3D", &IN::muIP3D);
  tree->SetBranchAddress("muIP3DErr", &IN::muIP3DErr);
  tree->SetBranchAddress("PFPhoEt", &IN::PFPhoEt);
  tree->SetBranchAddress("PFPhoEta", &IN::PFPhoEta);
  tree->SetBranchAddress("PFPhoPhi", &IN::PFPhoPhi);
  tree->SetBranchAddress("PFPhoType", &IN::PFPhoType);
  tree->SetBranchAddress("PFPhoIso", &IN::PFPhoIso);
  tree->SetBranchAddress("rho25", &IN::rho25);
  tree->SetBranchAddress("rho25_neu", &IN::rho25_neu);
  tree->SetBranchAddress("rho25_muPFiso", &IN::rho25_muPFiso);
  tree->SetBranchAddress("rho25_elePFiso", &IN::rho25_elePFiso);
  tree->SetBranchAddress("rho2011", &IN::rho2011);
  tree->SetBranchAddress("rho2012", &IN::rho2012);
  tree->SetBranchAddress("jetTrg", &IN::jetTrg);
  tree->SetBranchAddress("jetEn", &IN::jetEn);
  tree->SetBranchAddress("jetPt", &IN::jetPt);
  tree->SetBranchAddress("jetEta", &IN::jetEta);
  tree->SetBranchAddress("jetPhi", &IN::jetPhi);
  tree->SetBranchAddress("jetCharge", &IN::jetCharge);
  tree->SetBranchAddress("jetEt", &IN::jetEt);
  tree->SetBranchAddress("jetRawPt", &IN::jetRawPt);
  tree->SetBranchAddress("jetRawEn", &IN::jetRawEn);
  tree->SetBranchAddress("jetArea", &IN::jetArea);
  tree->SetBranchAddress("jetCHF", &IN::jetCHF);
  tree->SetBranchAddress("jetNHF", &IN::jetNHF);
  tree->SetBranchAddress("jetCEF", &IN::jetCEF);
  tree->SetBranchAddress("jetNEF", &IN::jetNEF);
  tree->SetBranchAddress("jetNCH", &IN::jetNCH);
  tree->SetBranchAddress("jetHFHAE", &IN::jetHFHAE);
  tree->SetBranchAddress("jetHFEME", &IN::jetHFEME);
  tree->SetBranchAddress("jetNConstituents", &IN::jetNConstituents);
  tree->SetBranchAddress("jetCombinedSecondaryVtxBJetTags", &IN::jetCombinedSecondaryVtxBJetTags);
  tree->SetBranchAddress("jetCombinedSecondaryVtxMVABJetTags", &IN::jetCombinedSecondaryVtxMVABJetTags);
  tree->SetBranchAddress("jetJetProbabilityBJetTags", &IN::jetJetProbabilityBJetTags);
  tree->SetBranchAddress("jetJetBProbabilityBJetTags", &IN::jetJetBProbabilityBJetTags);
  tree->SetBranchAddress("jetTrackCountingHighPurBJetTags", &IN::jetTrackCountingHighPurBJetTags);
  tree->SetBranchAddress("jetBetaStar", &IN::jetBetaStar);
  tree->SetBranchAddress("jetPFLooseId", &IN::jetPFLooseId);
  tree->SetBranchAddress("jetDRMean", &IN::jetDRMean);
  tree->SetBranchAddress("jetDR2Mean", &IN::jetDR2Mean);
  tree->SetBranchAddress("jetDZ", &IN::jetDZ);
  tree->SetBranchAddress("jetFrac01", &IN::jetFrac01);
  tree->SetBranchAddress("jetFrac02", &IN::jetFrac02);
  tree->SetBranchAddress("jetFrac03", &IN::jetFrac03);
  tree->SetBranchAddress("jetFrac04", &IN::jetFrac04);
  tree->SetBranchAddress("jetFrac05", &IN::jetFrac05);
  tree->SetBranchAddress("jetFrac06", &IN::jetFrac06);
  tree->SetBranchAddress("jetFrac07", &IN::jetFrac07);
  tree->SetBranchAddress("jetBeta", &IN::jetBeta);
  tree->SetBranchAddress("jetBetaStarCMG", &IN::jetBetaStarCMG);
  tree->SetBranchAddress("jetBetaStarClassic", &IN::jetBetaStarClassic);
  tree->SetBranchAddress("jetBetaExt", &IN::jetBetaExt);
  tree->SetBranchAddress("jetNNeutrals", &IN::jetNNeutrals);
  tree->SetBranchAddress("jetNCharged", &IN::jetNCharged);
  tree->SetBranchAddress("jetMVAs", &IN::jetMVAs);
  tree->SetBranchAddress("jetWPLevels", &IN::jetWPLevels);
  tree->SetBranchAddress("jetMt", &IN::jetMt);
  tree->SetBranchAddress("jetJECUnc", &IN::jetJECUnc);
  tree->SetBranchAddress("jetLeadTrackPt", &IN::jetLeadTrackPt);
  tree->SetBranchAddress("jetVtxPt", &IN::jetVtxPt);
  tree->SetBranchAddress("jetVtxMass", &IN::jetVtxMass);
  tree->SetBranchAddress("jetVtx3dL", &IN::jetVtx3dL);
  tree->SetBranchAddress("jetVtx3deL", &IN::jetVtx3deL);
  tree->SetBranchAddress("jetSoftLeptPt", &IN::jetSoftLeptPt);
  tree->SetBranchAddress("jetSoftLeptPtRel", &IN::jetSoftLeptPtRel);
  tree->SetBranchAddress("jetSoftLeptdR", &IN::jetSoftLeptdR);
  tree->SetBranchAddress("jetSoftLeptIdlooseMu", &IN::jetSoftLeptIdlooseMu);
  tree->SetBranchAddress("jetSoftLeptIdEle95", &IN::jetSoftLeptIdEle95);
  tree->SetBranchAddress("jetDPhiMETJet", &IN::jetDPhiMETJet);
  tree->SetBranchAddress("jetPuJetIdL", &IN::jetPuJetIdL);
  tree->SetBranchAddress("jetPuJetIdM", &IN::jetPuJetIdM);
  tree->SetBranchAddress("jetPuJetIdT", &IN::jetPuJetIdT);
  tree->SetBranchAddress("jetPartonID", &IN::jetPartonID);
  tree->SetBranchAddress("jetGenJetIndex", &IN::jetGenJetIndex);
  tree->SetBranchAddress("jetGenJetEn", &IN::jetGenJetEn);
  tree->SetBranchAddress("jetGenJetPt", &IN::jetGenJetPt);
  tree->SetBranchAddress("jetGenJetEta", &IN::jetGenJetEta);
  tree->SetBranchAddress("jetGenJetPhi", &IN::jetGenJetPhi);
  tree->SetBranchAddress("jetGenPartonID", &IN::jetGenPartonID);
  tree->SetBranchAddress("jetGenEn", &IN::jetGenEn);
  tree->SetBranchAddress("jetGenPt", &IN::jetGenPt);
  tree->SetBranchAddress("jetGenEta", &IN::jetGenEta);
  tree->SetBranchAddress("jetGenPhi", &IN::jetGenPhi);
  tree->SetBranchAddress("convVtx", &IN::convVtx);
  tree->SetBranchAddress("convVtxErr", &IN::convVtxErr);
  tree->SetBranchAddress("convPairMomentum", &IN::convPairMomentum);
  tree->SetBranchAddress("convRefittedMomentum", &IN::convRefittedMomentum);
  tree->SetBranchAddress("convNTracks", &IN::convNTracks);
  tree->SetBranchAddress("convPairInvMass", &IN::convPairInvMass);
  tree->SetBranchAddress("convPairCotThetaSep", &IN::convPairCotThetaSep);
  tree->SetBranchAddress("convEoverP", &IN::convEoverP);
  tree->SetBranchAddress("convDistOfMinApproach", &IN::convDistOfMinApproach);
  tree->SetBranchAddress("convDPhiTrksAtVtx", &IN::convDPhiTrksAtVtx);
  tree->SetBranchAddress("convDPhiTrksAtEcal", &IN::convDPhiTrksAtEcal);
  tree->SetBranchAddress("convDEtaTrksAtEcal", &IN::convDEtaTrksAtEcal);
  tree->SetBranchAddress("convDxy", &IN::convDxy);
  tree->SetBranchAddress("convDz", &IN::convDz);
  tree->SetBranchAddress("convLxy", &IN::convLxy);
  tree->SetBranchAddress("convLz", &IN::convLz);
  tree->SetBranchAddress("convZofPrimVtxFromTrks", &IN::convZofPrimVtxFromTrks);
  tree->SetBranchAddress("convNHitsBeforeVtx", &IN::convNHitsBeforeVtx);
  tree->SetBranchAddress("convNSharedHits", &IN::convNSharedHits);
  tree->SetBranchAddress("convValidVtx", &IN::convValidVtx);
  tree->SetBranchAddress("convMVALikelihood", &IN::convMVALikelihood);
  tree->SetBranchAddress("convChi2", &IN::convChi2);
  tree->SetBranchAddress("convChi2Probability", &IN::convChi2Probability);
  tree->SetBranchAddress("convTk1Dz", &IN::convTk1Dz);
  tree->SetBranchAddress("convTk2Dz", &IN::convTk2Dz);
  tree->SetBranchAddress("convTk1DzErr", &IN::convTk1DzErr);
  tree->SetBranchAddress("convTk2DzErr", &IN::convTk2DzErr);
  tree->SetBranchAddress("convCh1Ch2", &IN::convCh1Ch2);
  tree->SetBranchAddress("convTk1D0", &IN::convTk1D0);
  tree->SetBranchAddress("convTk1Pout", &IN::convTk1Pout);
  tree->SetBranchAddress("convTk1Pin", &IN::convTk1Pin);
  tree->SetBranchAddress("convTk2D0", &IN::convTk2D0);
  tree->SetBranchAddress("convTk2Pout", &IN::convTk2Pout);
  tree->SetBranchAddress("convTk2Pin", &IN::convTk2Pin);
};

void InitOUTTree( TTree * tree ) {
  tree->Branch("nVtxBS", &OUT::nVtxBS, "nVtxBS/I");
  tree->Branch("pfMET", &OUT::pfMET, "pfMET/F");
  tree->Branch("pfMETPhi", &OUT::pfMETPhi, "pfMETPhi/F");
  tree->Branch("pfMETsumEt", &OUT::pfMETsumEt, "pfMETsumEt/F");
  tree->Branch("pfMETmEtSig", &OUT::pfMETmEtSig, "pfMETmEtSig/F");
  tree->Branch("pfMETSig", &OUT::pfMETSig, "pfMETSig/F");
  tree->Branch("recoPfMET", &OUT::recoPfMET, "recoPfMET/F");
  tree->Branch("recoPfMETPhi", &OUT::recoPfMETPhi, "recoPfMETPhi/F");
  tree->Branch("recoPfMETsumEt", &OUT::recoPfMETsumEt, "recoPfMETsumEt/F");
  tree->Branch("recoPfMETmEtSig", &OUT::recoPfMETmEtSig, "recoPfMETmEtSig/F");
  tree->Branch("recoPfMETSig", &OUT::recoPfMETSig, "recoPfMETSig/F");
}
void CopyInputVarsToOutput( std::string prefix) {
    CopynVtxBSInToOut( prefix ); 
    CopypfMETInToOut( prefix ); 
    CopypfMETPhiInToOut( prefix ); 
    CopypfMETsumEtInToOut( prefix ); 
    CopypfMETmEtSigInToOut( prefix ); 
    CopypfMETSigInToOut( prefix ); 
    CopyrecoPfMETInToOut( prefix ); 
    CopyrecoPfMETPhiInToOut( prefix ); 
    CopyrecoPfMETsumEtInToOut( prefix ); 
    CopyrecoPfMETmEtSigInToOut( prefix ); 
    CopyrecoPfMETSigInToOut( prefix ); 
}

// The next set of functions allows one to copy 
// input variables to the outputs based on a key
// A copy function is generated for each pair of variables
// The copy function holds the name of the function to compare
// to the input key.  If the variables are vectors, a second function
// is generated that allows one to copy all variables matching a given key
// at a certain index and pushes that back on the output variable

void CopyPrefixBranchesInToOut( const std::string & prefix ) {
// Just call each copy function with the prefix 

    CopynVtxBSInToOut( prefix );
    CopypfMETInToOut( prefix );
    CopypfMETPhiInToOut( prefix );
    CopypfMETsumEtInToOut( prefix );
    CopypfMETmEtSigInToOut( prefix );
    CopypfMETSigInToOut( prefix );
    CopyrecoPfMETInToOut( prefix );
    CopyrecoPfMETPhiInToOut( prefix );
    CopyrecoPfMETsumEtInToOut( prefix );
    CopyrecoPfMETmEtSigInToOut( prefix );
    CopyrecoPfMETSigInToOut( prefix );
}; 

void CopyPrefixIndexBranchesInToOut( const std::string & prefix, unsigned index ) { 

// Just call each copy function with the prefix 

}; 

void ClearOutputPrefix ( const std::string & prefix ) {
}; 

void CopynVtxBSInToOut( std::string prefix ) { 

    std::string my_name = "nVtxBS";
    std::size_t pos = my_name.find( prefix ); 
    // if the filter is given only continue if its matched at the beginning 
    if( prefix != "" &&  pos != 0 ) return; 
  OUT::nVtxBS = IN::nVtxBS;
}; 

 void CopypfMETInToOut( std::string prefix ) { 

    std::string my_name = "pfMET";
    std::size_t pos = my_name.find( prefix ); 
    // if the filter is given only continue if its matched at the beginning 
    if( prefix != "" &&  pos != 0 ) return; 
  OUT::pfMET = IN::pfMET;
}; 

 void CopypfMETPhiInToOut( std::string prefix ) { 

    std::string my_name = "pfMETPhi";
    std::size_t pos = my_name.find( prefix ); 
    // if the filter is given only continue if its matched at the beginning 
    if( prefix != "" &&  pos != 0 ) return; 
  OUT::pfMETPhi = IN::pfMETPhi;
}; 

 void CopypfMETsumEtInToOut( std::string prefix ) { 

    std::string my_name = "pfMETsumEt";
    std::size_t pos = my_name.find( prefix ); 
    // if the filter is given only continue if its matched at the beginning 
    if( prefix != "" &&  pos != 0 ) return; 
  OUT::pfMETsumEt = IN::pfMETsumEt;
}; 

 void CopypfMETmEtSigInToOut( std::string prefix ) { 

    std::string my_name = "pfMETmEtSig";
    std::size_t pos = my_name.find( prefix ); 
    // if the filter is given only continue if its matched at the beginning 
    if( prefix != "" &&  pos != 0 ) return; 
  OUT::pfMETmEtSig = IN::pfMETmEtSig;
}; 

 void CopypfMETSigInToOut( std::string prefix ) { 

    std::string my_name = "pfMETSig";
    std::size_t pos = my_name.find( prefix ); 
    // if the filter is given only continue if its matched at the beginning 
    if( prefix != "" &&  pos != 0 ) return; 
  OUT::pfMETSig = IN::pfMETSig;
}; 

 void CopyrecoPfMETInToOut( std::string prefix ) { 

    std::string my_name = "recoPfMET";
    std::size_t pos = my_name.find( prefix ); 
    // if the filter is given only continue if its matched at the beginning 
    if( prefix != "" &&  pos != 0 ) return; 
  OUT::recoPfMET = IN::recoPfMET;
}; 

 void CopyrecoPfMETPhiInToOut( std::string prefix ) { 

    std::string my_name = "recoPfMETPhi";
    std::size_t pos = my_name.find( prefix ); 
    // if the filter is given only continue if its matched at the beginning 
    if( prefix != "" &&  pos != 0 ) return; 
  OUT::recoPfMETPhi = IN::recoPfMETPhi;
}; 

 void CopyrecoPfMETsumEtInToOut( std::string prefix ) { 

    std::string my_name = "recoPfMETsumEt";
    std::size_t pos = my_name.find( prefix ); 
    // if the filter is given only continue if its matched at the beginning 
    if( prefix != "" &&  pos != 0 ) return; 
  OUT::recoPfMETsumEt = IN::recoPfMETsumEt;
}; 

 void CopyrecoPfMETmEtSigInToOut( std::string prefix ) { 

    std::string my_name = "recoPfMETmEtSig";
    std::size_t pos = my_name.find( prefix ); 
    // if the filter is given only continue if its matched at the beginning 
    if( prefix != "" &&  pos != 0 ) return; 
  OUT::recoPfMETmEtSig = IN::recoPfMETmEtSig;
}; 

 void CopyrecoPfMETSigInToOut( std::string prefix ) { 

    std::string my_name = "recoPfMETSig";
    std::size_t pos = my_name.find( prefix ); 
    // if the filter is given only continue if its matched at the beginning 
    if( prefix != "" &&  pos != 0 ) return; 
  OUT::recoPfMETSig = IN::recoPfMETSig;
}; 

 