#ifndef BRANCHINIT_H
#define BRANCHINIT_H
#include "TTree.h"
#include "TChain.h"
void InitINTree( TChain * tree );
void InitOUTTree( TTree * tree );
void CopyInputVarsToOutput(std::string prefix = std::string() );
void CopyPrefixBranchesInToOut( const std::string & prefix );
void CopyPrefixIndexBranchesInToOut( const std::string & prefix, unsigned index );
void ClearOutputPrefix ( const std::string & prefix );
void CopynMCInToOut( std::string prefix = std::string() ); 
void CopymcPIDInToOut( std::string prefix = std::string() ); 
void CopymcPIDInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcPID( std::string prefix ); 
void CopymcVtx_xInToOut( std::string prefix = std::string() ); 
void CopymcVtx_xInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcVtx_x( std::string prefix ); 
void CopymcVtx_yInToOut( std::string prefix = std::string() ); 
void CopymcVtx_yInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcVtx_y( std::string prefix ); 
void CopymcVtx_zInToOut( std::string prefix = std::string() ); 
void CopymcVtx_zInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcVtx_z( std::string prefix ); 
void CopymcPtInToOut( std::string prefix = std::string() ); 
void CopymcPtInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcPt( std::string prefix ); 
void CopymcMassInToOut( std::string prefix = std::string() ); 
void CopymcMassInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcMass( std::string prefix ); 
void CopymcEtaInToOut( std::string prefix = std::string() ); 
void CopymcEtaInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcEta( std::string prefix ); 
void CopymcPhiInToOut( std::string prefix = std::string() ); 
void CopymcPhiInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcPhi( std::string prefix ); 
void CopymcEInToOut( std::string prefix = std::string() ); 
void CopymcEInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcE( std::string prefix ); 
void CopymcEtInToOut( std::string prefix = std::string() ); 
void CopymcEtInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcEt( std::string prefix ); 
void CopymcGMomPIDInToOut( std::string prefix = std::string() ); 
void CopymcGMomPIDInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcGMomPID( std::string prefix ); 
void CopymcMomPIDInToOut( std::string prefix = std::string() ); 
void CopymcMomPIDInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcMomPID( std::string prefix ); 
void CopymcMomPtInToOut( std::string prefix = std::string() ); 
void CopymcMomPtInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcMomPt( std::string prefix ); 
void CopymcMomMassInToOut( std::string prefix = std::string() ); 
void CopymcMomMassInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcMomMass( std::string prefix ); 
void CopymcMomEtaInToOut( std::string prefix = std::string() ); 
void CopymcMomEtaInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcMomEta( std::string prefix ); 
void CopymcMomPhiInToOut( std::string prefix = std::string() ); 
void CopymcMomPhiInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcMomPhi( std::string prefix ); 
void CopymcIndexInToOut( std::string prefix = std::string() ); 
void CopymcIndexInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcIndex( std::string prefix ); 
void CopymcDecayTypeInToOut( std::string prefix = std::string() ); 
void CopymcDecayTypeInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcDecayType( std::string prefix ); 
void CopymcParentageInToOut( std::string prefix = std::string() ); 
void CopymcParentageInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcParentage( std::string prefix ); 
void CopymcStatusInToOut( std::string prefix = std::string() ); 
void CopymcStatusInToOutIndex( unsigned index, std::string prefix = std::string() ); 
void ClearOutputmcStatus( std::string prefix ); 
#endif
